### ISSUE TITLE
Un problema al intentar compilar con gcc

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#1]
Hola, mi problema es que cuando intento usar gcc para compliar me aparece esto:

/usr/include/glib-2.0/glib/gtypes.h:32:24: fatal error: glibconfig.h: No existe el archivo o el directorio

En una parte encontré que puede servir hacer esto:
export CPATH=$CPATH:/usr/lib/glib-2.0/include/
 
Esto se hacía con varios directorios, y de esta manera, efectivamente el error va cambiando, porque empezó con 

probando.c:2:21: fatal error: gtk/gtk.h: No existe el archivo o el directorio
compilation terminated.

Sin embargo, siguen apareciendo errores, ¿debería seguir exportando? Gracias

**Comment by Ghoeb** [comment]
Hola! En qué sistema operativo estás trabajando? Y qué es lo que intentas compilar? El hola mundo te funciona? Porque no vamos a usar GTK+ todavía.

**Comment by Ghoeb** [comment]
Y, perdona, los ejemplos del repositorio deben compilarse con 

```
make
```

Mi plan era ver eso mañana.

**Comment by AlfonsoIgnacioV** [comment]
Hola! Ya me resultó, gracias!
