### ISSUE TITLE
Tiempo de ejecución de la tarea

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#10]
Hola! En mi PC el programa original que nos pasaron como ejemplo (el que invierte los colores) ya se demora como un segundo o más en ejecutarse y en el enunciado dice que se va a cortar luego de un segundo el programa. ¿Qué tan estrictos van a ser en ese sentido, considerando lo anterior? Mi programa actualmente corre en un tiempo un poco mayor a eso, pero funciona... Eso, para poder tenerlo en cuenta.
Gracias :)

**Comment by Ghoeb** [comment]
Es un segundo en mi computador, considerando que el programa que dices no demora absolutamente nada. Tu tranquilo.

**Comment by jnrosenb** [comment]
Pregunta similar a esta. Estaba midiendo los tiempos de ejecucion usando el comando time de la terminal, y vi que con imagenes de tamaños cercanos a 1920x1080 ya empieza a retornar tiempos de 1 segundo y a veces un poco mas. ¿Hay algun tamaño maximo de imagen que podamos usar de referencia para ver si nuestro programa cumple los tiempos?

**Comment by Ghoeb** [comment]
@jnrosenb Muy buena pregunta. Las tareas serán corregidas con imágenes de 512x512, para mantener un orden de ejecución razonable.

**Comment by fjvalles** [comment]
¿Cómo puedo ver cuánto se demora mi programa? ¿Hay algún comando o tengo que escribir un código para verlo?

**Comment by Ghoeb** [comment]
En la consola, el comando `time`. Se escribe antes de tu programa:

```sh
time ./tuprograma [...]
```

**Comment by spiza** [comment]
cuál es el detalle que entrega time?

A mí me sale esto;

`0.07s user 0.01s system 23% cpu 0.360 total`

**Comment by Ghoeb** [comment]
El user time es el que importa(el primero), lo otro es cuanto tiempo estuvo efectivamente corriendo tu programa.
