### ISSUE TITLE
Problema con valores de delta_x y delta_y

### ISSUE THREAD

**Issue by fjvaldes1** [IIC2133-PUC/2016-2#11]
Hola!
Tengo el siguiente código dentro del main:
int delta_x = *argv[3]; 
int delta_y = *argv[4];
printf("delta_x: %d",delta_x);
printf("delta_y: %d",delta_y);

Al pasarle como argumentos delta_x=-5 y delta_y=-10 (hago "make" y después "valgrind ./jisterize clownfish.png resultado.png -5 -10"), no se por qué lo que se imprime es:
"delta_x: 45"
"delta_y: 45"

¿Qué puedo estar haciendo mal?
Muchas gracias!

**Comment by josegonzalezc** [comment]
los parámetros tienes que convertirlos a int primero con la función atoi() :

int delta_x =atoi(argv[3]);

después de eso debería funcionar bien.

**Comment by Ghoeb** [comment]
@fjvaldes1 es exactamente lo que dice tu compañero.

**Comment by fjvaldes1** [comment]
Gracias! Ahí me funcionó
