### ISSUE TITLE
Guía con el informe

### ISSUE THREAD

**Issue by carlosgarciag** [IIC2133-PUC/2016-2#12]
Estimados,

¿Es posible que nos puedan mostrar un informe del semestre pasado como para ver bien qué se espera de los análisis de complejidad?

De antemano, muchísimas gracias.

¡Saludos a todos!

**Comment by vicentemartintarud** [comment]
¿Qué se espera del análisis de en uso de memoria?

Gracias!

**Comment by Ghoeb** [comment]
@carlosgarciag No tengo ejemplos para pasarles de informes anteriores, dado que los problemas son demasiado distintos. Se espera, en todo caso, que incluyan un procedimiento al menos como el visto en la ayudantía, o si quieren irse a la segura, lo visto en Matemáticas Discretas. No es necesario que sea 100% formal, pero sí serio y bien justificado.

@vicentemartintarud El procedimiento es el mismo que para el tiempo de ejecucion, solo que en lugar de fijarte en la cantidad de operaciones, revisas cuanto espacio se esta usando para almacenar los elementos. Por ejemplo, un arreglo de _n_ elementos de tamaño _k_ va a usar siempre _n*k_ en memoria. Dado que _k_ es una constante, el uso de memoria de un arreglo de _n_ elementos es _O(n)_, por lo que cualquier algoritmo que use un arreglo es al menos _O(n)_ en uso de memoria.

**Comment by AlfonsoIgnacioV** [comment]
Hola! Y qué cosas podemos asumir?? 
Me pasó que necesito usar un teorema para poder explicar una complejidad de un algoritmo. 
En otro caso me pasó que necesito explicar que un orden de magnitud es mayor que otro, pero no sé si puedo asumirlo.
Y en otro caso necesito explicar algo por recursión con el teorema, y de nuevo, no sé si esa noción se puede asumir
Gracias :)

**Comment by Ghoeb** [comment]
No te estoy pidiendo que demuestres nada ni que reinventes la rueda. Perfectamente puedes decir "y por el teorema maestro, tenemos [...]", por ejemplo. No tienes que demostrar que 11 > 10 para poder usarlo tampoco :disappointed: 

Aprovecha los dominios de las variables que controlan la complejidad, por ejemplo "podemos dividir todos los terminos por _X_ ya que sabemos que _X_ > 0"

En resumen, lo que sea que pongas estará correcto siempre y cuando esté bien justificado, ya sea por lo que hayas dicho anteriormente o por materia vista en clases.

**Comment by AlfonsoIgnacioV** [comment]
Ok, gracias :)

**Comment by fimuniz** [comment]
Hola!
Para hacer el análisis de complejidad tengo que considerar las iteraciones que hago para liberar memoria? y los tiempos de la libreria se consideran O(1) o debemos considerarlos?

**Comment by tamycova** [comment]
y para el análisis de tiempo, puedo considerar n como el número de pixeles? en vez de decir que es n² pensando en n como ancho de la matriz (asumiendo que es cuadrada?), o mejor uso a*b con a ancho y b largo?

**Comment by vdrg** [comment]
#14 Aquí hay más info sobre lo que deben tomar en cuenta para calcular la complejidad.

@tamycova da lo mismo si eliges usar el número total de pixeles o el ancho y largo por separado. Mientras el análisis esté bien y lo expliques, no hay problema.
