### ISSUE TITLE
Acerca del bonus

### ISSUE THREAD

**Issue by fjvalles** [IIC2133-PUC/2016-2#13]
¿Alguien sería tan amable de orientarme en cuanto a la búsqueda de la tecnología que permitiría aplicar el filtro a la imagen en O(1) por favor? He estado algunas horas buscando y nada.

**Comment by Ghoeb** [comment]
Es el bonus, así que no puedo darte la respuesta.

Pero, si te sirve de algo, esa misma tecnología es muy útil para procesamiento de imágenes en general, para poder acelerar las **convoluciones**.

Pero la respuesta no es única, todo depende de como lo justifiques.
