### ISSUE TITLE
Sobre la complejidad en librería.

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#14]
Hola! Mi duda es si debemos considerar en el análisis los costos en librería que esta tenga "por detrás", ejemplo en la función stbi_write_png, o podemos asumir que no superan el orden de nuestro programa?
Espero se entienda, gracias :)

**Comment by vdrg** [comment]
Hola!
Cuando hablamos de la complejidad de su algoritmo nos referimos a la parte en la que se le aplica el filtro al imagen, no cuando se lee/escribe/libera memoria.

Lo otro que habían preguntado antes: la complejidad es con respecto al input, que en este caso sería el número de pixeles, ya que la cantidad de operaciones que se hagan sólo dependerá de que tan grande sea la imagen (a menos que estén haciendo algo mal :cry: ).
