### ISSUE TITLE
Sobre el orden de la carpeta

### ISSUE THREAD

**Issue by saalba** [IIC2133-PUC/2016-2#15]
Para la entrega se haran descuentos si dentro de las carpetars originales hay elementos extras a lo entregado inicialmente como el ejecutable o las carpetas object?

**Comment by vdrg** [comment]
No somos tan malos jaja pero idealmente no pongan nada, quizás para las próximas tareas especificaremos que no suban cosas extras (supusimos que no lo harían, ya que así se pide en la mayoría de los ramos del DCC). El ejecutable eso si no lo pongan, pa que no tengamos problemas al corregir.

PD: igual si te fijas el directorio que contiene los .o no se subirá al repo, porque en el .gitignore se excluyen esos archivos, y como el directorio estará "vacío" (según git) no se subirá. En cambio el ejecutable no tiene extensión por lo que no podemos agregarlo al .gitignore.

**Comment by vdrg** [comment]
IMPORTANTE: el makefile y los archivos originales tienen que estar donde mismo, porque para corregir usamos un script que asumirá que todo está donde tiene que estar. 

Si tienen archivos de código extra dentro del directorio "jisterize" no hay problema.
