### ISSUE TITLE
Dudas Tarea 1

### ISSUE THREAD

**Issue by Geeermy** [IIC2133-PUC/2016-2#16]
¡Hola! Tengo tres dudas en particular, y agradecería mucho si me las despejaran c:

1. Hay un caso del enunciado que no me queda muy claro, es con respecto al paso 2:

"Las dos cadenas que quedan cierran el espacio que dejó el grupo anterior. Si esto forma un grupo de 2 o más elementos adyacentes del mismo símbolo, ese grupo se elimina y se repite el paso 2. Si no, termina el proceso de inserción."

¿Esto es solo si la inserción del paso 1 elimina un grupo que no se encuentre en los extremos?

Por ejemplo:

alpha = AABBCC
beta = ABC

AABBCC => AAABBCC => BBCC => CC => Vacío

Es el mismo ejemplo del enunciado, solo que si siguiéramos el paso 2, se nos iría todo con la primera inserción. Pero esto solo ocurre si el paso 2 incluye los grupos de los extremos. ¿Cómo lo consideraremos finalmente?

2. ¿Podría la cadena beta tener elementos que no se encuentran en la cadena alpha? Por ejemplo:

alpha = ABC
beta = ABCD

Sé que es un caso "tonto", pero es para ver si sería pertinente hacer un filtro inicial antes o si "todo me sirve".

3. Aprovechando que aún no suben los repositorios... al igual que para la T0, ¿se incluirá todo ya organizado en un main.c y un MakeFile? ¿o lo hacemos todo desde 0? (para avanzar en las estructuras que quiero implementar desde ya).

¡De antemano gracias! :D

**Comment by Geeermy** [comment]
PD: Como copié esto de un correo, la numeración de las preguntas murió jaja.

**Comment by alopez7** [comment]
Cuando elimines un grupo de caracteres del lado, no tienes que unir la cadena con nada. Ej:
alpha = ABC
betha = AABBCC

AABBCC -0-> BBCC -0-> CC -0-> vacío

Solo ejecutas el paso 2 si la cadena queda cortada

**Comment by Ghoeb** [comment]
Mira, respondiendo tus preguntas en orden:

1) Modificaré un poco tu ejemplo:

alpha = AABBCC
beta = BAC

Insertemos un B en la mitad:

AABBCC ---2--> AABBBCC => AA + CC => AACC

Ahora, si insertamos un A al principio... 

AACC ---2--> AAACC => (vacio) + CC => CC

...son realmente casos distintos?

1) Sí, definitivamente sí. Por ejemplo:
alpha = AA
beta = CCC

AA ---1--> ACA ---1--> ACCA ---1--> ACCCA => AA => (vacío)

1) Sí, les subiremos un pequeño código base, pero un _main_ donde se leerá y escribirá un archivo, nada más que eso. Por mientras modela tu programa y trabaja con los ejemplos del enunciado directo en tu código.

Espero que haya quedado claro. Saludos!

**Comment by Geeermy** [comment]
Quedó todo muy claro.

¡Muchas gracias a ambos! :)
