### ISSUE TITLE
Make no funciona

### ISSUE THREAD

**Issue by DibPuelma** [IIC2133-PUC/2016-2#18]
Probablemente mi pregunta es muy básica, pero al hacer make dentro de la carpeta programa me da el siguiente error:

error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'

Lei que se integró en BASH 4.2 y OS X no tiene esa versión. Hay alguna solución?

Edit: en el makefile le saqué el -Og a la línea 21 y funciona, pero no se si va a afectar cuando corrijan la tarea

**Comment by Ghoeb** [comment]
Lo siento, es un flag que puse por mejor, pero parece no funcionar en Mac OSX. Tiene que ver con la versión del compilador `gcc` y no de Bash en todo caso. Lo que busca es lo siguiente:

`-g` significa agregar a cada parte del código un indicador de la linea que le corresponde, para que al usar `valgrind` o `gdb` para debugear te va a decir "error en linea `x`, función `y` de `archivo.c`" en lugar de simplemente aparecer la dirección de memoria de la función.

`-O[...]` significa optimizar: hace que tu código quede al menos 2 veces más rápido (quizás 3 o 4). El problema es que al optimizar se desordena mucho el código, por lo que cuando estes debugeando, `valgrind` o `gdb` te van a decir "error en la linea `x`" y esa linea no va a ser la correcta.

`-Og` es "optimiza todo lo que puedas sin desordenar el código, de manera de que debugear sea fácil"

Es decir, para debugear tu programa, usa `-g`, pero a la hora de entregarlo, déjalo con `-O3` (es el máximo) de manera de que el programa corra tan rápido como pueda. Conste, si tu programa tiene errores de memoria (de los que reporta `valgrind`) es posible que se te caiga al correrlo con optimizaciones.
