### ISSUE TITLE
Secuencias sin solución

### ISSUE THREAD

**Issue by flobarrios** [IIC2133-PUC/2016-2#19]
Hola! se asume que todas las secuencias tendrán solución o puede pasar que se pruebe con casos que no la tengan ? En ese caso, como debería ser el output? 

Gracias!

**Comment by Ghoeb** [comment]
Pueden asumir tanto que todo el input que les pasemos estará bien formado y que todos los problemas serán resolvibles.

Saludos!

**Comment by flobarrios** [comment]
Gracias!
