### ISSUE TITLE
Problema al compilar

### ISSUE THREAD

**Issue by nigfasa** [IIC2133-PUC/2016-2#2]
Queria probar el ejemplo de la Tarea0, pero al hacerle un make al main, dice que:

"
/tmp/ccBRsbIi.o: En la función `main':
main.c:(.text+0x6e): referencia a `load_image_rgb' sin definir
main.c:(.text+0x10c): referencia a `write_image_rgb' sin definir
collect2: error: ld returned 1 exit status
"
pero sé que "load_image_rgb" y "write_image_rgb" estan definidas ya que al comienzo del archivo fueron agregadas con: #include "../imagelib/imagelib.h". 

Le he dado algunas vueltas al codigo, pero prefiero preguntar ya que tal vez sea algun error sin relación alguna a esto. 

Gracias

**Comment by AlfonsoIgnacioV** [comment]
hola! Me pasa el mismo error cuando le hago gcc directamente (con make me funciona bien, pero obviamente no hace nada).
Le cambié esa línea por : #include "../imagelib/imagelib.c", notar que al parecer (no estoy seguro), pero creo que esa debió ser la referencia. Sin embargo, ahora me aparece esto. Cuando hago
$ gcc main.c -o main_

Me sale lo siguiente:
/tmp/ccSOFFbW.o: En la función `stbi__ldr_to_hdr':
main.c:(.text+0x1a3e): referencia a `pow' sin definir
/tmp/ccSOFFbW.o: En la función `stbi__hdr_to_ldr':
main.c:(.text+0x1bc2): referencia a `pow' sin definir
collect2: error: ld returned 1 exit status

Estuve intentando entender este error sin éxito. 
Tengo dos preguntas...
1) ¿En verdad era : #include "../imagelib/imagelib.h" o más bien : #include "../imagelib/imagelib.c"? Que fuera la primera no me hace mucho sentido, por el orden en que están definidos.
2) ¿Qué significa el segundo error? 
Espero responda tu duda.
Gracias!

**Comment by Ghoeb** [comment]
Hola! En respuesta a sus preguntas

-> Importar el .h es correcto
-> El segundo error significa que no se está agregando la librería math.h, pero eso es porque lo estás compilando con gcc siendo que tienes que usar make. 

Necesito que me respondan las siguientes preguntas para poder ayudarlos:
1) En que sistema operativo están?
2) En que directorio están llamando a make?
3) Los ejemplos del repositorio principal les funcionan?

**Comment by vdrg** [comment]
@AlfonsoIgnacioV Se incluyen los .h (headers) porque ahí se declaran las funciones, luego el compilador (gcc) se encarga del .c.

Por favor prueben lo siguiente:

1. Pararse dentro del directorio "Programa/src/jisterize"
2. Ejecuten `gcc -o jisterize main.c ../imagelib/imagelib.c -lm`

**Comment by AlfonsoIgnacioV** [comment]
Hola, hice lo que decía  @vdrg y efectivamente, ahora el programa funciona. Sin embargo, no entiendo qué es lo que hace jisterize exactamente como archivo compilado. Me refiero a que no sé qué archivo está corriendo, porque pareciera no estar compilando un archivo en específico (como para verlo y ver cómo incluir las imágenes para empezar a probarlo). 
Respondiendo a  @Ghoeb 
1) Estoy en Linux
2) Lo estaba llamando desde Programas
3) ¿Hablas de las fotos? Esas no las he probado, aun no veo esa parte. Si son las del primer ejemplo que subieron como hace una semana, esas sí me funcionaron :)

Gracias!

**Comment by vdrg** [comment]
@AlfonsoIgnacioV cuando haces `make` o el comando que escribí más arriba se crea un archivo que se llama "jisterize". Éste es el programa compilado, el cual ejecutas así: `jisterize source.png target.png`, donde source.png es la imagen que se le entrega al programa y target.png es el nombre de la imagen que el programa creará (tienes que tener source.png en el mismo directorio en el que estás ejecutando el programa, o puedes llegar a ella usando un path relativo, ../../imagen.png, por ejemplo).

**Comment by Ghoeb** [comment]
Ya, que es lo que pasa, es que la corrección se hace de manera automatizada, por lo que necesito que funcione `make` con sus tareas. Esto es por varias razones:

* Para compilar las tareas que vienen necesitarán usar `make`, porque compilar con **GTK+** requiere varios parámetros adicionales, así que necesito que aprendan a usarlo ahora.
* En caso de que quieran organizar su programa en submódulos (.h + .c) puedan hacerlo sin complicaciones, ya que mi _Makefile_ detecta automáticamente lo que haya en los directorios especificados.
* En caso de que quieran usar alguna librería misteriosa que requiera parámetros adicionales para compilar, pueden agregarlas al comando de compilación, y así las tareas de todos se compilan igual

Sus repositorios son (o eran inicialmente) una copia exacta del [repo base de la T0](https://github.com/IIC2133-PUC/T0Base)

Siguiendo las instrucciones del enunciado, debería funcionar abrir la terminal (<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>) pararse en el directorio _Programa_ e invocar `make`, y en ese mismo directorio debería generarse el ejecutable llamado `jisterize`, el cual pueden ejecutar diciendo `./jisterize source.png target.png` (nótese, siempre parados en el directorio _Programa_)

Avisen como les va, me es importante que les funcione `make`

**Comment by nigfasa** [comment]
Funciona ahora  al :100:  el make 

Graaacias

**Comment by AlfonsoIgnacioV** [comment]
A mí también :D 
Gracias!!
