### ISSUE TITLE
Alcances y consejos [Tarea 1]

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2016-2#21]
Estimados, si bien en el enunciado les dimos consejos sobre como atacar un problema de backtracking, quería darles un consejo sobre este problema en específico, además de en que deberían enfocarse y en que no.

* En primer lugar, los tests solo usan caracteres de la A a la Z, por lo que pueden perfectamente usar otros caracteres para representar distintas cosas a lo largo de su secuencia. En particular una buena idea es envolver la secuencia alpha con dos caracteres "vacíos", de manera de ahorrarse todos los casos borde de inserción y revisión de grupos en caso de agregar algo en alguno de los dos extremos. Por ejemplo:

Definimos `'#'` como el caracter vacío. Entonces la secuencia alpha, que originalmente era

`QUNXQOOQHWWHNUQ`

ahora queda como 

`#QUNXQOOQHWWHNUQ#`

ahora las operaciones de insercion al principio y al final de la lista no tienen que manejar los nulos. Y dado que el caracter vacío nunca coincidirá con un elemento de alpha o beta, la revisión de los grupos simplemente no lo considera.

* Segundo, en otro issue un alumno preguntó sobre el flag `-Og` en la `Makefile`. #18 
Según la versión del compilador / terminal que tengan, el flag `-Og` podría no funcionar. Para irse a la segura reemplácenlo por `-g` y a la hora de entregar lo entregan con `-O3`. El tiempo límite que dicta la pauta será corriéndola con `-O3`, así que no quieren perder la velocidad extra.

* Por último, si les complica el que tan buena es su solución, les diré que se espera que la implementen en base a listas doblemente ligadas, **sin** usar necesariamente podas o heurísticas, como dice en el enunciado. Aunque nunca está demás la velocidad :wink: 

Saludos!

**Comment by vicentemartintarud** [comment]
Respecto a lo último, nuestra solución sin podas debiese ser capaz de resolver todos los tests subidos en menos de 10 segundos?
Pregunto porque mi tarea soluciona un par de tests en el tiempo que corresponde, pero para otros toma bastante tiempo.

Saludos!

**Comment by alopez7** [comment]
Para obtener la nota máxima en la parte de código, debes poder resolver los ejemplos antes de que se corten por tiempo. Para hacer más rápido tu programa, puedes hacer varias cosas:

- Usar estructuras de datos que hagan más rápido las operaciones que no tienen que ver directamente con backtracking (insertar un elemento, eliminar elementos, volver a insertar los elementos eliminados, etc...).
- Optimizar tu algoritmo: A veces pasa que puedes estar haciendo muchas operaciones innecesarias que hacen muy lenta la búsqueda, y que se podría optimizar si se revisa el código.
- Implementar podas: Si tienes una buena modelación del problema, no debería ser difícil implementar podas simples. Una poda muy simple puede mejorar mucho la eficiencia del algoritmo.

**Comment by AntoniaMendoza** [comment]
Lo del tiempo < 10 segundos es sin usar valgrind cierto?

**Comment by Ghoeb** [comment]
@AntoniaMendoza sí, absolutamente. valgrind hace que los programas corran ~40x más lento, y sólo se ejecuta una vez que ya pasaron el test para hacer análisis de uso de memoria.
