### ISSUE TITLE
Duda Solución Ayudantía 3, Ej 3.1

### ISSUE THREAD

**Issue by DibPuelma** [IIC2133-PUC/2016-2#22]
En el código sale lo siguiente

if (iz == -1 || der == - 1){
  return -1
}
if (|iz - der| > 1){
  return -1
}

Para qué sirve el segundo if? Mirándolo veo que la única opción de que la condición se cumpla es que iz sea 1 y der -1 o iz sea -1 y der 1 y en ese caso ya habríamos entrado en el if anterior.

Gracias

**Comment by alopez7** [comment]
Las variables iz y der son la cantidad de pisos de los hijos izquierdo y derecho respectivamente (-1 si el hijo está desbalanceado).
Si la diferencia de altura de los hijos es mayor a 1, entonces está desbalanceado el árbol.

Un ejemplo donde pasa esto es el siguiente:
                          7
           3                            8
   1            5                 
0    2      4    6 

El algoritmo se da cuenta de que está desbalanceado cuando la raíz recibe iz = 2, y der = 0.
En ese caso la diferencia es igual a 2, por lo que entra al if  (|iz - der| > 1).

Espero esto resuelva tu duda

**Comment by DibPuelma** [comment]
Entiendo, muchas gracias!
