### ISSUE TITLE
Notas T0

### ISSUE THREAD

**Issue by djpassi** [IIC2133-PUC/2016-2#25]
Hola!

Cuando estarán las notas de la T0? Principalmente me interesa la nota del informe, para saber en que nos equivocamos y no caer en lo mismo en el informe de la T1.

Saludos!!

**Comment by Ghoeb** [comment]
Esta semana. Aunque las cosas que se piden en la T0 son muy distintas a lo que pedimos en la T1, por lo que no sé que tan útil te puede ser.

**Comment by djpassi** [comment]
Gracias!
