### ISSUE TITLE
Duda enunciado Tarea 1

### ISSUE THREAD

**Issue by DibPuelma** [IIC2133-PUC/2016-2#27]
En el enunciado sale lo siguiente: 

Las dos cadenas que quedan cierran el espacio que dejó el grupo anterior. Si esto forma un grupo de 2 o más elementos adyacentes del mismo símbolo, ese grupo se elimina y se repite el paso 2. Si no, termina el proceso de inserción.

Voy a explicar mi duda con un ejemplo:

Imaginemos que tenemos la cadena
ABBJJA

A esta le insertamos una J en la posicion 3, quedando
ABBJJJA, por lo que eliminamos el trío

ABBJJJA -> ABBA.

En este caso se eliminan o no las B?, por el enunciado me tinca que no, pero no queda claro.

Saludos y gracias.

**Comment by Ghoeb** [comment]
Dice que se elimina sólo si **forman** un grupo (negrita incluída). Ahi no se está formando ningún grupo: ese grupo de dos Bs ya existía antes.

**Comment by DibPuelma** [comment]
Perfecto muchas gracias!
