### ISSUE TITLE
Plazo Tarea 1

### ISSUE THREAD

**Issue by djpassi** [IIC2133-PUC/2016-2#28]
Hola,

Me gustaría saber si pueden definir el plazo de la Tarea 1. Muchos dependemos de ese plazo para poder organizarnos en base a nuestras actividades personales.

Por mi parte sería ideal si pueden fijar este plazo para el Jueves-Viernes. Me gustaría saber si hay mas gente que piense esto mismo para que así los encargados vean si se puede hacer algo al respecto.

Saludos,

**Comment by Ghoeb** [comment]
Hola

Se dijo a principio de semestre que no se daría plazo adicional para ninguna tarea, ya que son demasiados alumnos como para tener que recalendarizar todas las evaluaciones. 

Pese a todo, se les dio más plazo para esta tarea, pero siendo una instancia excepcional se les da como penalización la incertidumbre. 

La Tarea 1 se entrega la otra semana. Les avisaremos con 24 horas de anticipación si esto es el Lunes 12 a las 23:59, o como máximo, el Viernes 16 a las 23:59.

Solo voy a decir que lo más probable es que esto sea el Miércoles, y luego menos probable Martes o Jueves. Lunes y Viernes es muy poco probable.

Saludos!
