### ISSUE TITLE
Resultado enunciado y tests

### ISSUE THREAD

**Issue by tamycova** [IIC2133-PUC/2016-2#29]
Hola!
1. En este ejemplo del enunciado, hubiera sido igual de válido que retorne 4? 
<img width="236" alt="screen shot 2016-09-10 at 4 47 19 pm" src="https://cloud.githubusercontent.com/assets/11545206/18413159/5cd315d0-7776-11e6-946a-d16874e71328.png">
2. Estos son los resultados que me dio con los tests, por si alguien quiere comparar! (si ven un error me avisan).

T01
2
1
1
T02
3
5
5
1
T03
2
1
1
T04
4
0
11
6
3
T05
4
23
0
49
24
T06
6
0
13
8
4
7
4
T07
4
36
39
10
7
T08
5
8
5
13
17
9
T09
4
17
2
10
3
T10
5
15
15
7
4
3
T11
4
15
13
4
4
T12
3
106
25
24

**Comment by Ghoeb** [comment]
Sí, es igual de válido :)

**Comment by sedelacerda** [comment]
Me dio exactamente los mismos resultados :smile:

**Comment by spiza** [comment]
Tuve un par de diferentes, pero más que nada porque en tu programa decía 1-18 x ejemplo, y en el mio 0 - 19

Saludos!

**Comment by spiza** [comment]
Distintos;

T04
4
1
10
6
3
T05
4
23
1
48
24
T06
6
1
6
9
4
7
4

**Comment by AntoniaMendoza** [comment]
Aquí van los algunos míos por si a alguien más le sirve
(no los revisé todos si)
T06:
0
13
8
4
7
4
T07:
36
39
10
7
T08:
8
5
13
17
9
T09:
17
2
10
3
T10:
15
15
7
4
3
T11:
15
13
4
4
T12:
106
25
24
