### ISSUE TITLE
Función get_pixel() y memory leaks

### ISSUE THREAD

**Issue by djpassi** [IIC2133-PUC/2016-2#3]
Hola,

Es necesario ver los casos borde dentro de la función **get_pixel** o podemos hacer todo dentro del main?

Otra consulta,
Al correr el ejemplo que viene escrito de invertir los colores, ejecuto valgrind y me dice que no hay memory leaks, está bien esto? En que caso deberían haber leaks si es que no hacemos ningún allocate de la memoria?

Gracias!

**Comment by vdrg** [comment]
Hola!

1. Pueden hacer lo que quieran, donde quieran (excepto obviamente en la librería).
2. No, de hecho si hay leaks de memoria en el ejemplo. No hay leaks de memoria si lo corres así: `valgrind ./jisterize`, porque como no le pasas argumentos, el programa termina antes de hacer cualquier asignación de memoria. El ejemplo se usa así: `jisterize source.png target.png`, donde source es la imagen que se le entrega al programa y target es el nombre de la imagen que el programa creará.

Cualquier cosa nos avisas.

**Comment by djpassi** [comment]
Gracias!
Me faltó poner los argumentos en valgrind de nuevo, pensé que quedaban guardados de la última ejecución que si tenía esos parámetros.
