### ISSUE TITLE
Leaks código base

### ISSUE THREAD

**Issue by tamycova** [IIC2133-PUC/2016-2#30]
Hola valgrind en el main que nos dan retorna:
LEAK SUMMARY:
==2211==    definitely lost: 0 bytes in 0 blocks
==2211==    indirectly lost: 0 bytes in 0 blocks
==2211==      possibly lost: 2,064 bytes in 1 blocks

De donde podría venir ese possibly lost? lo ignoro?

Gracias

**Comment by Ghoeb** [comment]
Hola, estás corriendo el programa en Linux? Recuerda que `valgrind` en OSX puede dar falsos positivos. Asegúrate de probarlo en Ubuntu

De todos modos, pídele a `valgrind` que te reporte el detalle completo de los leaks: debería aparecer el nombre de las funciones culpables

* Si esa función es tuya o fue llamada por una función tuya, partiste a arreglar tu código
* Si esa función es de los strings: `strxxx` o `memxxx`, es posible que sea por que le estás pasando strings mal formados como parámetro (aunque eso debería generar errores de memoria, no leaks)
* Si la función es alguna cosa rara, y el stack de llamada no tiene ninguna función tuya, eso es sospechoso y hay que verlo caso a caso.

Saludos!

**Comment by tamycova** [comment]
Es el main base! sin funciones mías, lo correré en ubuntu y te cuento :)

**Comment by djpassi** [comment]
Que raro! Corrí el código base en mac y no me dio problemas
`==19682== LEAK SUMMARY:
==19682==    definitely lost: 0 bytes in 0 blocks
==19682==    indirectly lost: 0 bytes in 0 blocks
==19682==      possibly lost: 0 bytes in 0 blocks
==19682==    still reachable: 0 bytes in 0 blocks
==19682==         suppressed: 26,222 bytes in 185 blocks`

**Comment by Ghoeb** [comment]
Esos que sale "supressed" siguen siendo leaks, solo que se le dijo a valgrind que los ignorara a la hora de hacer la cuenta.

**Comment by djpassi** [comment]
Gracias, debe haber sido que lo corría en mac. En ubuntu tira esto (a mi código en especifico)

> ==2444== 
==2444== HEAP SUMMARY:
==2444==     in use at exit: 0 bytes in 0 blocks
==2444==   total heap usage: 44 allocs, 44 frees, 2,207 bytes allocated
==2444== 
==2444== All heap blocks were freed -- no leaks are possible
==2444== 
==2444== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==2444== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by Ghoeb** [comment]
"**All heap blocks were freed -- no leaks are possible**" 

eso es lo que tu quieres oir ;)
