### ISSUE TITLE
Output T1

### ISSUE THREAD

**Issue by spiza** [IIC2133-PUC/2016-2#31]
Hola!

Pregunta! 

Quisiera saber cuál será la nomenclatura del output de salida.. Por ejemplo, considerese ;

Alfa = UWU
Beta = WW

un output válido sería por ejemplo;

2
1
1
así como también podría ser
2
2
3

Lo digo porque en mi código insertar en la posición 0 implica mover todo el segmento alfa hacia adelante un espacio.

Pregunto para no tener dramas después!

Saludos!

**Comment by Ghoeb** [comment]
Si, el estandar al insertar un elemento en un índice especifico de una lista es que el elemento queda en ese índice, y el que estaba ahí y el resto se mueven hacia la derecha un índice.

Ambas soluciones son correctas: para evaluar se ejecutarán cada una de sus instrucciones. Si eso destruye la secuencia alfa, entonces es correcto.

**Comment by spiza** [comment]
perfecto.. consulta, podrían subir el archivo con el cual van a corregir las tareas? 

O sea, el algoritmo verificador de resultados, jajaja, para re-asegurarme de que está bien!

**Comment by Ghoeb** [comment]
Lo siento, no puedo ya que hace uso de todas las estructuras y funciones que se supone que tienen que implementar ustedes.
