### ISSUE TITLE
Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by mf222** [IIC2133-PUC/2016-2#32]
Estoy implementando una lista doblemente ligada, el programa no se cae, pero me da este error
```
Conditional jump or move depends on uninitialised value(s)
```
Puse como opción en valgrind `--track-origins=yes` y me da también `Uninitialised value was created by a heap allocation`. El error me sale cuando inserto y elimino. Alguna idea de lo que esta pasando y como solucionarlo? :sob:

**Comment by Ghoeb** [comment]
Cuando tengas un puntero sin asignar, asegurate de setearlo explícitamente a `NULL`. En general son `NULL` por defecto, pero no hay garantía de eso, por eso `valgrind` se queja :)

**Comment by mf222** [comment]
Pero no tengo punteros sin asignar :worried: osea tengo 2, head* y tail* que los uso en estos metodos, pero los definí como null D:

**Comment by mf222** [comment]
HE MENTIDO! Efectivamente era un puntero al que no había explicitado como `NULL` (no lo había visto con tanta línea de código :see_no_evil: )

Gracias!!!
