### ISSUE TITLE
Problema compilando (make reduce)

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#34]
Hola, es una duda con el make. El make no me deja, estando en la carpeta Programa, crear un reduce con make, considerando que no he modificado absolutamente nada todavía. Me está tirando un error:

Mensajes del ensamblador:
Error fatal: no se puede crear obj/imagelib/imagelib.o: No existe el archivo o el directorio
Makefile:59: fallo en las instrucciones para el objetivo 'obj/imagelib/imagelib.o'

¿Se supone que ya viene en el formato en que debería compilar o ejecutarse o hay que crear algo aparte de modificar la función? 
Muchas gracias
Saludos

**Comment by vdrg** [comment]
Rarísimo, acabo de probarlo y si funciona. Ejecutaste `make` estando en el directorio Programa?

Puedes tratar también creando el directorio "obj" dentro de Programa, pero no debería ser necesario.

**Comment by AlfonsoIgnacioV** [comment]
si, estoy en Programa. Me funciona si creo una carpeta obj que tenga las mismas carpetas que tiene src, pero vacías. No sé si eso es bueno, pero ahora anda bien
Gracias!

**Comment by vdrg** [comment]
Dale, que bueno que funcionó. Me haces un favor? Puedes decirme donde clonaste tu repo y qué comandos utilizaste (por ejemplo si usaste sudo en algún lado)? 

Se supone que el Makefile debería crear los directorios automáticamente, así que quiero ver si tu error es culpa nuestra o si hubo algo raro en el proceso de clonado. Gracias!

**Comment by AlfonsoIgnacioV** [comment]
Lo cloné en el escritorio... Luego usé simplemente los comandos de make reduce (desde la carpeta Programa). Luego lo corrí desde ahí mismo en Programa, usando ./reduce imagen_origen.png imagen_destino.png n. No usé sudo en ningún momento.
Con la creación de una carpeta obj y los archivos vacíos dentro cuyos nombres son los del src, funciona perfect. Si no los creo, me alega porque no existen.
Saludos! :) Espero sirva

**Comment by vdrg** [comment]
Gracias! El problema es que estás haciendo `make reduce`, pero tienes que ejecutar solamente `make`.
