### ISSUE TITLE
Median cut: Lab v/s RGB

### ISSUE THREAD

**Issue by rpalmaotero** [IIC2133-PUC/2016-2#35]
En el enunciado de la T2 dice que el *clustering* mediante *median cut* va a dividir sucesivamente según la mediana de algún eje Lab. Sin embargo, también dice que no todos los colores Lab mapean a colores RGB válidos. Es equivalente calcular la paleta usando colores Lab que usando RGB?

**Comment by Ghoeb** [comment]
No, no es equivalente. La paleta calculada con _Lab_ es de mejor calidad. Además, si bien no todos los colores _Lab_ son válidos, todos los colores iniciales del problema sí lo son. El promedio entre colores válidos también es válido, por lo que no deberías preocuparte por eso.

**Comment by rpalmaotero** [comment]
Impecable. Gracias.

**Comment by rpalmaotero** [comment]
Sorry, se me olvidó algo: para elegir el canal por el cuál ordenar los pixeles tengo que elegir el que tenga mayor rango. En el caso de RGB todos los canales van de 0 a 255, pero en *Lab* el canal *L* puede ir de 0 a 100 y los otros dos van desde -128 hasta 128. Debo normalizar los valores de los canales al usar *Lab* para elegir el de mayor rango?

**Comment by Ghoeb** [comment]
Buena pregunta. Eso no lo habíamos considerado. Por ahora trabajalo sin normalizar, te haré saber como hay que hacerlo correctamente.

**Comment by vdrg** [comment]
No hay que normalizar!
