### ISSUE TITLE
Plazo entrega Tarea 2

### ISSUE THREAD

**Issue by dfleider** [IIC2133-PUC/2016-2#37]
Hola!

Podrían por favor dar mas plazo para entregar la T2? Esta demasiado copada esta semana y va a ser dificil el hecho de que también tenemos prueba de EDD el día anterior a la fecha actual de entrega.

Muchas gracias

**Comment by Ghoeb** [comment]
Lo consideraré

**Comment by vicentemartintarud** [comment]
Habrá más tiempo?

Gracias!
