### ISSUE TITLE
Normalizacion y k maximo

### ISSUE THREAD

**Issue by sedelacerda** [IIC2133-PUC/2016-2#38]
Cerraron el issue anterior en el que hablaban sobre la normalización de las dimensiones y no alcancé a preguntar sobre esto.

1. Esta prohibido que normalicemos las dimensiones para encontrar la paleta de colores? O no es necesario que normalicemos? Hice la prueba y por lo menos en mi caso me resulta mucho mejor normalizar.

2. Pueden decir qué tan grande será el máximo input k que usarán para corregir la tarea? Tengo problemas cuando uso k's mayores que 8 y sospecho que es por que uso ints de 8 bits.

3. Podrían subir algunos tests? :D

Gracias!

**Comment by Ghoeb** [comment]
A nosotros normalizar nos daba malos resultados, ya que dado que el rango de L es menor, tiende a cortar todo según L, pero si tu de algún modo lo haces funcionar y reduce tu error, bienvenido sea

0 < k < 24

No hace diferencia, pero considera que probaremos con imágenes 1920 x 1080

**Comment by andersskog** [comment]
Sobre el k máximo, si en una imagen 1920 x 1080 tomamos un k = 23, buscaremos una paleta de 8.388.608 colores distintos, siendo que la imagen solo tendrá 1920 x 1080 = 2.073.600. Esto provocará que el median cut entregue clusters sin pixeles y, por lo menos en mi código, lleva a un error. 

Por lo tanto, podemos asumir que el k máximo será 20, para que así la paleta de colores tenga sentido? Si no, como solucionamos el tema de los clusters vacios? los ignoramos?

Gracias

**Comment by alopez7** [comment]
Si llegas a esa situación, en que la paleta es más grande que la cantidad de colores en la imagen (porque hay más colores que pixeles), entonces puedes tomar como paleta a todos los colores distintos de la imagen. Eso lo puedes hacer calculando antes de crear el árbol, o creando un árbol que se de cuanta cuando una caja está vacía. Sea como sea la solución que implementes, te recomiendo explicarlo en el informe.
En todo caso no creo que tomemos k tan grande como para que se de ese problema, ya que no tiene sentido para lo que se busca en el enunciado.

**Comment by hjquiroga** [comment]
El programa me corre bien con k hasta 15 mas o menos. Cuando ingreso un k mayor a 20 me entrega segmentation fault debido a que la paleta de colores es un arreglo y he excedido el tamaño maximo de un arreglo. El enunciado no hacía mención a los k máximos, pero por lo leido aquí debo entonces crear una nueva estructura que soporte mayor tamaño para almacenar la paleta?

**Comment by alopez7** [comment]
Puede ser porque estás creando el arreglo como colores[tamaño], pero debes crear los arreglo en el heap con malloc, y luego liberas los arreglos que no necesitas. De esta manera usas mucho menos espacio.

**Comment by tamycova** [comment]
@Ghoeb no se si se refieren a esto cuando hablan con la normalización, pero cómo debería enfrentar elegir el eje que tiene mayor rango en median cut? considerando que el rango de L es menor a los de a y b, debería tomarlo de forma absoluta o "porcentual" (supongo que a eso se referían con lo de normalización)?

**Comment by Ghoeb** [comment]
@tamycova si, efectivamente nos referimos a eso. Hay que tomarlo de manera absoluta, un rango de a = [-60, 60] es mayor a un rango de L = [0,100], por mucho que eso signifique <50% en a, y 100% en L.

**Comment by tamycova** [comment]
@Ghoeb gracias! y otra duda de median cut, cuando separo por la mitad los "buckets" si el número es par, por ejemplo 4, 2 para un lado y 2 para el otro, pero si el número es impar, qué minimizaría el error? por ejemplo con 5, A) Siempre el sobrante al bucket de los más chicos, 3 para un lado y 2 para el otro (o de los más grandes) o B) Ponerlo en los dos lados, 3 para un lado y 3 para el otro

**Comment by Ghoeb** [comment]
Lo normal es tirar todo lo menor o igual a la mediana a la izquierda, y el resto a la derecha. Recuerda que este algoritmo es una aproximación de la solución, por lo que efectivamente se dan casos como ese donde la respuesta correcta no es clara.

Si implementan median-cut correctamente sin mejoras de ustedes deberían poder generar una imagen de igual calidad que la pauta.
