### ISSUE TITLE
Duda estabilidad mergesort

### ISSUE THREAD

**Issue by jatrincado** [IIC2133-PUC/2016-2#39]
Por ahí estuve leyendo que mergesort es estable, pero en el algoritmo de la diapositiva de la clase no me queda claro (ordenación diap. 34). ¿Debería ser una comparación con a[p].key <= a[q].key para que no se desordene el orden original de valores iguales (y sea estable)?

**Comment by yadran** [comment]
Supongamos que inicialmente a[3] = a[29] = 11.  Hay que preguntarse, ¿cuántas veces
son comparados a[3] y a[29] entre ellos? y ¿qué hace el algoritmo cuando determina que
son iguales?  Ciertamente, en el arreglo final deben quedar contiguos, p.ej., en a[j] y a[j+1];
entonces, ¿cuál queda en a[j] y cuál en a[j+1]?  --Yadran


On Oct 2, 2016, at 12:05 PM, jatrincado wrote:


Por ahí estuve leyendo que mergesort es estable, pero en el algoritmo de la diapositiva de la clase no me queda claro (ordenación diap. 34). ¿Debería ser una comparación con a[p].key <= a[q].key para que no se desordene el orden original de valores iguales (y sea estable)?

**Comment by jatrincado** [comment]
Como lo entiendo yo, a[3] y a[29] se compararían entre ellos sólo una vez, en la cual a[3] está en la mitad izquierda, y a[29] está en la mitad derecha. Como la comparación es (en la diapositiva) menor estricta, se ejecuta el else, por lo que sería a[29] el que queda en a[j], y a[3] quedaría en a[j+1], ¿o me equivoco?
