### ISSUE TITLE
Editor (Atom vs Sublime)

### ISSUE THREAD

**Issue by tamycova** [IIC2133-PUC/2016-2#4]
Hola!

Quería saber si hay alguna razón en específico por la que en la wiki recomiendan Atom para trabajar con C, o puedo trabajar bien igual con Sublime 3?

Gracias!

**Comment by vdrg** [comment]
Puedes usar lo que quieras (yo no uso ninguno de los 2)! Lo importante es que puedan configurarlo bien con los plugins que hay para que se les facilite el desarrollo, y atom tiene infinitos plugins para C. No cacho mucho sublime 3 pero supongo que también debe tener varias herramientas para eso.

Conclusión: lo que te acomode más.

**Comment by tamycova** [comment]
Buenísimo, gracias!
