### ISSUE TITLE
Colores el L*ab

### ISSUE THREAD

**Issue by afcerna** [IIC2133-PUC/2016-2#40]
No me funciona correctamente la paleta cuando ocupo valores negativos de b. Por ejemplo el valor L=100, a=0, b=0 es correctamente un blanco, pero al usar los valores L=100, a=0, b=-1, me cambia de forma abrupta a un color amarillo. 

![ex](https://cloud.githubusercontent.com/assets/11434052/19116663/aadae580-8aec-11e6-9d69-1b63e9f685c0.png)

La página que estoy usando para ver los colores es http://colorizer.org/

**Comment by Ghoeb** [comment]
No entiendo a que te refieres, la librería toma (100,0,-1) como amarillo? Lab tiene muchas variantes. Nosotros estamos trabajando con la que usa Matlab. 

El objetivo de la tarea es que generes los colores a partir de los que vienen en la imagen, no a mano.

**Comment by afcerna** [comment]
Lo que ocurre es que uno de los colores de mi paleta entrega el valor L=100, a=0, b=-1. Y viendo la imagen original este corresponde a un blanco (o un valor cercano), pero al settear ese pixel con el valor de la paleta, la imagen en lugar de ser blanca en el fondo, es amarilla.

![ex](https://cloud.githubusercontent.com/assets/11434052/19123821/b09b3c3a-8b06-11e6-9591-c0f874d729e4.png)

Mi duda es si tan solo un cambio en la unidad del canal b, puede cambiar tanto la imagen, ya que con valores de L=100, a=0, b=0 el fondo es blanco.

**Comment by Ghoeb** [comment]
Y cual es la imagen original?

**Comment by Ghoeb** [comment]
En todo caso, me da la impresion de que Lab(100,0,-1) no es un color RGB válido

**Comment by afcerna** [comment]
Entiendo. Y sacando el promedio de un número de puntos válidos es posible llegar a un punto inválido?

**Comment by Ghoeb** [comment]
No debería ser posible. Por qué no me mandas la imagen original?

**Comment by afcerna** [comment]
![charmander](https://cloud.githubusercontent.com/assets/11434052/19131581/5560aa74-8b26-11e6-9196-60da1b0cb2c4.png)
Ya arreglé la funcion premedio que estaba dividiendo por un número menos de lo debido y funciona. =)
