### ISSUE TITLE
Copiar Imagen

### ISSUE THREAD

**Issue by spiza** [IIC2133-PUC/2016-2#41]
Hola! Tengo problemas para copiar la imagen.. Sé que es fácil, pero me travé en esto :(

Alguien me puede echar una manito? Deben ser como 3 líneas de código, jajaja

Saludos

**Comment by spiza** [comment]
@Ghoeb ; @vdrg 

Porfa ayúdenme!! no puedo seguir trabajando en la tarea si no logro copiar la imagen ImageLab :(

**Comment by vdrg** [comment]
Hola

No es necesario copiar la imagen, sólo tienes que copiar el arreglo de pixeles para trabajar con ellos haciendo median cut (o el algoritmo que hayas elegido). Una vez que tienes la paleta "óptima" (que es un arreglo de Pixel_labs) reemplazas los colores en la imagen original.

Para copiar el arreglo de pixeles puedes usar memcpy o crear un arreglo nuevo e iterar.
