### ISSUE TITLE
Tiempo de ejecución

### ISSUE THREAD

**Issue by vaopaso** [IIC2133-PUC/2016-2#42]
Hola, tengo un problema porque en el enunciado dice que el algoritmo será cortado después de 10 segs de ejecución. Además en otro issue dijeron que iban a probar con fotos 1080x1920.

Considerando esto, el problema está en que no logro que el medianCut me corra en menos de 10 segs para el caso en que k>=4 (para fotos 1080p), en donde me da aprox 12segs (k=4).
Ya verifiqué mi método y lo traté de hacer eficiente pero nose si me falta algo. Prácticamente hace solamente sus 2 llamadas recursivas, y además ocupa el quickselect, que es lo que más demora, pero este ya no se puede hacer más eficiente. El proceso de todo el medianCut y de sus varios quickselects internos que hace (que estos también son recursivos) representan casi todo el tiempo de ejecución. Además se pierden aprox 1.75 segs en los módulos de lectura (los que no teníamos que tocar), entonces en verdad no sé que hacer con el tema del tiempo. Puede ser que consideren más tiempo de ejecución o consideren fotos más chicas?? O que puedo estar haciendo mal para que me corra rápido??

**Comment by Ghoeb** [comment]
La razón por la que la tarea se trata de completar una función es porque así podemos medir cuanto se toma la parte de ustedes, vs los modulos de lectura y escritura.

Se me ocurre que en cada paso del median-cut estás revisando en que eje estás, y según eso comparas. Te puedes ahorrar la revisión de eje si a la funcion median-cut le pasas como parámetro la función comparadora, tal como la que se usa con `qsort` de la librería estandar. Revisalo [aquí](http://www.geeksforgeeks.org/comparator-function-of-qsort-in-c/).

**Comment by Ghoeb** [comment]
Ahora, es posible que te este dando el peor caso de quick select que es O(n²), quizas te convenga más usar otro algoritmo de búsqueda de mediana como "Median of medians"

**Comment by Ghoeb** [comment]
Quizás estés cayendo en el caso malo del algoritmo de selección. Quizas te sirva partir de un pivote aleatorio.

**Comment by tamycova** [comment]
@vaopaso prueba con median3 en el quickselect o quizas con un cutoff, osea por ejemplo para un rango <10 usar insertionsort en vez de quickselect para dejar la mediana donde quieres, a mi me sirvio para optimizar!

**Comment by VictorVidaurre** [comment]
¿Los test de pruebas se corren solamente una vez? 
Me pasa que en promedio para imágenes de 1920x1080 con k=20 se demora 9,2 segundos, pero de vez en cuando pasa los 10 segundos. ¿Qué pasaría en el caso de que justo durante la corrección esa iteración pase los 10 segundos, siendo que en promedio toma menos tiempo?

**Comment by Ghoeb** [comment]
Se corren solo una vez. Estás considerando el tiempo de lectura / escritura de imágenes para medir el tiempo?

K = 20 es muy alto en todo caso, no probaré con eso
