### ISSUE TITLE
Imagenes Grandes

### ISSUE THREAD

**Issue by spiza** [IIC2133-PUC/2016-2#44]
... Tengo un problema y no sé porqué me está pasando.

Cuando trato de hacer algo con imagenes mayores o iguales a 1920x1080, me lanza segmentatio fault.. luego de cortar la imagen un poco (1917x1080), funciona.. No sé qué pasa..

**Comment by vaopaso** [comment]
anda probando con print's en el código pa ver en donde se produce el error.

**Comment by Ghoeb** [comment]
Corre tu programa con valgrind para saber la operación exacta que produce el error. Si es que estás pidiendo mucha más memoria que la disponible, malloc retornará NULL.

**Comment by spiza** [comment]
Efectivamente corrí el programa en valgrind, y me funcionó, pero lanzó muchos más errores de los que lanza cuando las imagenes son más pequeñas.

Qué puedo hacer ante esto? el malloc falla, y tengo pocos memory leaks :(

**Comment by Ghoeb** [comment]
Estás copiando el arreglo cada vez? Asegurate de liberarlo entre paso y paso para tener memoria disponible... 

Que dice valgrind entonces? no me quedó claro.
