### ISSUE TITLE
Error "Usage: example source target colors"

### ISSUE THREAD

**Issue by tumunoz** [IIC2133-PUC/2016-2#45]
Hola, cuando hago ./reduce myimage.png myimage2.png me está tirando " Usage: example source target colors".  Alguna idea de que puedo haber roto? 

Gracias!

**Comment by vdrg** [comment]
Tienes que darle un 'k' también, `./reduce img1 img2 k`.

Lee el enunciado para que sepas qué es 'k'

**Comment by tumunoz** [comment]
jajajaj que imbecil, gracias!
