### ISSUE TITLE
Invalid read and Invalid write of size 8

### ISSUE THREAD

**Issue by tamycova** [IIC2133-PUC/2016-2#47]
Hola!
Tengo esta función muy simple que calcula el minimo de un arreglo. Si comp es 0 por ejemplo, elem seria arr[i].L (un double). Al agregar la línea de current_min = elem valgrind se vuelve loco tirando errores, pero los dos son doubles, no sé que pasa atrás :( algo con ese retorno que accede a la struct quizás?

<img width="505" alt="screen shot 2016-10-07 at 8 20 09 pm" src="https://cloud.githubusercontent.com/assets/11545206/19207987/98598cdc-8ccb-11e6-97c4-be10e3a701df.png">

**Comment by tamycova** [comment]
Me pasa lo mismo si trató de hacer printf("%lf\n",arr[i].L ); (arr es mi copia del arrai de Color_labs que hice iterando)

**Comment by Onavila** [comment]
Tengo entendido que ese error surge cuando intentas leer un dato que no tienes, el i se estaría escapando del arreglo. Si es eso, el problema no sería la función, sino el como manejas el right (o el left).

**Comment by Ghoeb** [comment]
Que errores te tira valgrind? Eso podría explicar muchas cosas.
