### ISSUE TITLE
Pasar array por valor en vez de por referencia

### ISSUE THREAD

**Issue by fjvaldes1** [IIC2133-PUC/2016-2#48]
Hola, tengo la siguiente duda:
Estoy tomando la imagen y aplicandole quickselect repetidas veces para armar el kd-tree. Sin embargo, esto cambia el array de pixeles de forma definitiva, pues en C tengo entendido que no se pueden pasar arrays por valor a una función, por lo que pierdo la imagen que tenía en un comienzo, es decir, los cambios hechos a la imagen quedan guardados. 
¿Cómo podría solucionar esto?
Gracias!

**Comment by saalba** [comment]
Me pasa lo mismo, se me desordenan los pixeles de la imagen original aunque cree un nuevo arreglo de Colores al cual le paso los punteros, no he logrado arreglarlo.

**Comment by Ghoeb** [comment]
No hay forma de prevenir eso excepto haciendo todo el trabajo de construccion del arbol / paleta con una copia del arreglo original.

**Comment by saalba** [comment]
Yo estoy haciendo lo siguiente ara hacer la copia del arreglo original:
Color_lab* pixels = calloc(size, sizeof(Color_lab*));
  for(int x = 0; x < size; x++){
    pixels[x] = image->pixels[x];
  }
por que de igual manera me cambia la posicion de pixeles de la imagen?

**Comment by Ghoeb** [comment]
Estás declarando mal el arreglo: debería ser calloc(size, sizeof(Color_lab)); dado que cada elemento del arreglo es un Color_lab y no un Color_lab*, así que sí o sí te vas a salir del arreglo y quien sabe sobre que estás escribiendo.

**Comment by saalba** [comment]
Buena!!! ahi me funciono bien, muchas gracias!

**Comment by fjvaldes1** [comment]
A mí también, gracias!
