### ISSUE TITLE
Imagenes de prueba para t2

### ISSUE THREAD

**Issue by pdpino** [IIC2133-PUC/2016-2#49]
Podrían subir imágenes reducidas de prueba para ver qué tan bueno es nuestro programa?
Probé con las que están en el enunciado pero encontré que tienen más colores de los que dice (quizás es porque al ponerla o sacarla del pdf se transforma a otro formato, o algo así)
Gracias!

**Comment by Ghoeb** [comment]
Si, el pdf es solo referencial, para que no pesaran tanto pasamos todas las imágenes a jpg, y eso las destruye.

Yo ya dije que usaríamos imágenes 1920 x 1080, y que el k sería tal que 2^k sería menor a la cantidad total de pixeles de la imagen.
