### ISSUE TITLE
Duda sobre la precedencia de los operadores & y ->

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#5]
Hola, si se tiene una línea de código de este estilo:
&a -> b
¿Cuál de los dos operadores se aplica primero? 
Llevándolo al caso real, en el main de la tarea aparece:
return &image -> [x][y]
Sin embargo, no tendría mucho sentido aplicarle un puntero a algo que ya es un puntero (en este caso image)
Espero se entienda
Gracias!

**Comment by Ghoeb** [comment]
@AlfonsoIgnacioV : Primero,

```c
return &image->pixels[x][y];
```
no es lo mismo que 
```c
/* Esta sintaxis es inválida */
return &image->[x][y];
```
Como habrás visto, la función de la que hablas tiene como tipo de retorno un puntero a un color, `Pixel_rgb*`, por lo que podrías inferir cual es la precedencia: &(image->pixels[x][y]). 

Esto permite modificarlo desde fuera:

```c
/* Puedes hacer */
pixel -> R = 255 - pixel -> R;
/* En lugar de tener que hacer */
image -> pixels[x][y] -> R = 255 -> image -> pixels[x][y] -> R;
/* Controlar los casos borde en este caso es mucho más engorroso */
```

Saludos!

**Comment by AlfonsoIgnacioV** [comment]
Dale, me había equivocado al escribirlo, me quedo claro. Gracias :)
