### ISSUE TITLE
mediana o promedio

### ISSUE THREAD

**Issue by hjquiroga** [IIC2133-PUC/2016-2#50]
Mi programa esta funcionando bien para k hasta 18. Una opción para disminuir la complejidad del algoritmo median cut puede ser cargar en la paleta de colores las medianas de cada partición que este genera, en vez de cargar el promedio (nos ahorramos el tiempo de calcular el promedio). Esta esto permitido en la tarea?

**Comment by Onavila** [comment]
No creo porque la mediana se saca sobre un solo color. Ademas, no te ahorrarias mucho tiempo, sacar los promedios es O(n), con n el número de pixeles. La unica forma de mejorar la solucion es escoger un buen candidato a mediana en el quicselect, o usar medians of medians
