### ISSUE TITLE
Tiempo de busqueda en arbol kd-tree

### ISSUE THREAD

**Issue by jlires** [IIC2133-PUC/2016-2#52]
Mi programa es muy lento a la hora de encontrar el color más cercano, una vez ya construido el árbol y todo, y no entiendo que parte del algoritmo de búsqueda del vecino mas cercano lo ocasiona. Mi código es algo como esto:

```
void recursive(current_node)  {
 if current_node == NULL {
  return;
 }
 if(distance(current_node.color, best)) < best_dist) {
  best_dist = distance(current_node.color, best);
  best = current_node;
 }
 if(image_color[i] < current_node.color[i]) {
  recursive con lado izquierdo;
  if( abs(current_node.color[i] – image_color[i]) < best_dist) {
   recursive con lado derecho;
  }
 } else {
  recursive con lado derecho;
  if( abs(current_node.color[i] – image_color[i]) < best_dist) {
   Recursive con lado izquierdo;
 }
}

global best = palette_root;
global best_dist = INFINITY;
recursive(palette_root);

```
PS: El programa llega a tardar hasta 1 minuto con k mayores a 15

**Comment by Ghoeb** [comment]
Estas haciendo mal la búsqueda. En primer lugar haz una búsqueda codiciosa, asignando el color del nodo en el que cae el punto. Para eso tienes que ir viendo a que lado de los planos ir moviéndote.

Una vez que eso te funcione, toma ese nodo y desde ahí hacia arriba revisas los árboles vecinos a ver si podría haber un color más cercano dentro de ellos (para hacer eso haces el mismo proceso de manera recursiva).

Eso es lo que se vio en la ayudantía.

**Comment by jlires** [comment]
Si, no pude ir a la ayudantía :(
Otra duda que me surgió es que en la construcción de mi árbol cada nodo, sea hoja o no, es un punto (un color) y he visto que se puede definir como que cada nodo es el valor y el eje donde se dividió en dos partes y recién en las hojas están los puntos.
¿Cuál de las dos es la correcta?

**Comment by Ghoeb** [comment]
Para esta tiene mas sentido dejar los puntos en las hojas.

**Comment by jlires** [comment]
Vale, gracias.
