### ISSUE TITLE
Borré makefile en último commit válido

### ISSUE THREAD

**Issue by carlosgarciag** [IIC2133-PUC/2016-2#54]
Estimados,

Me acabo de dar cuenta que borré el makefile por accidente en mi último commit de la tarea. Espero que no sea un gran inconveniente para ustedes. En todo caso, hice otro commit agregándolo, pero fuera de plazo.

Perdón por las molestias.

Saludos.

**Comment by Ghoeb** [comment]
Eso no es problema ya que para esta tarea tu código se va a compilar incluyéndolo a otro código base.
