### ISSUE TITLE
Dimensiones Mapa

### ISSUE THREAD

**Issue by spiza** [IIC2133-PUC/2016-2#56]
Hola! Tengo otra pregunta :-P

Quisiera saber cuáles serán las dimensiones máximas del mapa que nos darán, así como también me gustaría saber cuántos bloques de hielo como máximo también nos darán.

Muchas gracias!

PD: Datos que me sirven como parámetros para algunas funciones.

**Comment by Ghoeb** [comment]
En principio no están acotados. Puedes asumir que te cabrán si o si en un `int`
