### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by fjvaldes1** [IIC2133-PUC/2016-2#57]
Hola, no entiendo a qué se refiere cuándo piden explicar "Cuál es el intervalo más pequeño que contiene su recorrido (de la tabla de hash)"

Gracias

**Comment by alopez7** [comment]
Tu función de hash tiene un dominio y un recorrido. Cuando se pide el intervalo más pequeño que contiene su recorrido, se está preguntando entre que intervalo quedan los resultados de la tabla de hash.
Por ejemplo, si tengo una matriz de NxN con elementos entre 1 y 10 y hago una función de hash para matrices que suma los valores de la matriz. 
En ese caso el mínimo valor que toma el recorrido de mi función de hash es N*N, y el máximo es 10*N*N, por lo que el intervalo más pequeño que contiene el recorrido es [N*N, 10*N*N]

**Comment by Ghoeb** [comment]
Nótese que las funciones de hash no siempre van a tomar todos los valores del intervalo: por eso se pide calcular este, ya que se puede ver facilmente cual es el valor máximo que puede tomar, y el mínimo. Identificar el recorrido exacto es una tarea completamente no trivial, por eso no les pedimos eso

Si el recorrido de una funcion h para el dominio D es R = {1,3,5,7,9}, el intervalo más pequeño que contiene al recorrido es el intervalo [1,9].

**Comment by rpalmaotero** [comment]
No me queda muy clara la pregunta. Esperan que calculemos el hash desde el mínimo valor posible de las llaves, hasta el máximo valor posible, y después determinar el intervalo del recorrido que fue efectivamente usado?
