### ISSUE TITLE
Más dudas

### ISSUE THREAD

**Issue by spiza** [IIC2133-PUC/2016-2#58]
Con respecto al bloque de hielo dice:

> Puede ser empujado en una dirección siempre que la celda opuesta no sea un bloque de hielo ni un muro de roca

Lo que no me queda claro es si los bloques de hielo pueden también pasar a través del antihielo (suena estúpido, pero mejor no quedar con la duda).

Otra duda es; en el caso de que puedan "subirse" a un antihielo, habrán antihielos en la mitad de la cancha, o siempre estarán para delimitar?

Gracias :-P

**Comment by spiza** [comment]
Me surgió otra más... El mapa, será así mismo como lo entregaron ustedes, o será un mapa sin espacios entre los caracteres?

**Comment by Ghoeb** [comment]
* Los bloques de hielo no se pueden subir a un antihielo, se frenan antes de que eso pase.
* Por lo mismo, habrá antihielos en cualquier parte del mapa (aunque siempre habrán también para delimitar)
* El enunciado dice que el mapa tiene espacios entre los caracteres, eso se mantiene.

**Comment by DibPuelma** [comment]
Entonces cuál es la diferencia entre el antihielo y el muro de roca?

**Comment by Ghoeb** [comment]
@DibPuelma el antihielo permite empujar desde esa dirección. El muro de roca (y el bloque de hielo) no.

**Comment by spiza** [comment]
O sea que si hay una situación así 

```
# # # # # # # #
# X _ _ _ _ _ #
# _ o _ _ _ _ #
# _ _ _ _ _ H # <--
# H _ _ _ _ _ #
# _ _ _ _ H _ #
# _ _ _ _ _ _ #
# # # # # # # #
```
Puedo mover el bloque marcado hacia la izquierda?

**Comment by Ghoeb** [comment]
Sí, definitivamente. Pero no hacia la derecha.

**Comment by marianoll** [comment]
Espera, si hay dos bloques de hielo juntos, no puedo empujar desde uno de ellos al otro? al igual que con los muros de roca?

**Comment by Ghoeb** [comment]
Exacto
