### ISSUE TITLE
Problema tarea 0

### ISSUE THREAD

**Issue by bregonesi** [IIC2133-PUC/2016-2#6]
Para los casos bordes estoy usando la función `get_pixel`, esta la llamo dentro del segundo `for`. Después de algunas iteraciones el valor de `image->width` dentro de esa función cambia a 0. 

Arregle esto haciendo una variable que guarda el valor del width de la imagen antes de entrar al for y la envío cada vez que llamo la función. A pesar de que esto funciona, es como una solución parche. Por que me pasa lo anterior?

En ningún momento toco la imagen original (como para que el width de este cambie).

**Comment by Ghoeb** [comment]
Lo probaste con `valgrind`? Revisa que es lo que te dice al respecto. Mi impresión es que te estás saliendo de `pixels` y modificando `width` por accidente.

**Comment by bregonesi** [comment]
Actualmente lo tengo con `width` (que es un parámetro de `get_pixel`) en vez de `image->width`. La imagen sale bien, pero cuando uso `image->width` se me cae por que me salgo de los pixeles (por que `image->width` toma el valor de cero, entonces si le resto algo se sale de los pixeles). Voy a ver nuevamente si funciona y ver lo que me dice `valgrind`.

**Comment by Ghoeb** [comment]
Me refiero a salirte de `image->pixels` y modificar `image->width`. Guíate según lo que dice `valgrind` para saber donde exactamente estás cometiendo la falta.

**Comment by bregonesi** [comment]
Encontre la falla. Gracias!
