### ISSUE TITLE
Tests, Límites y Hash [Tarea 3]

### ISSUE THREAD

**Issue by Ghoeb** [IIC2133-PUC/2016-2#61]
Les tengo 3 tests para que prueben su tarea. Su código debería poder resolverlos fácilmente en menos de un segundo.

```
5
7
# # # # #
# _ _ H #
# _ _ _ #
# _ o _ #
# _ _ _ #
# H _ H #
# # # # #

```

---

```
6
6
# # # # # #
# X _ _ H #
# _ o _ _ #
# _ _ o _ #
# H _ _ H #
# # # # # #

```

---

```
7
7
# # # # # # #
# _ _ _ _ H #
# _ _ _ _ _ #
# _ _ o _ _ #
# _ _ _ _ _ #
# H _ _ _ H #
# # # # # # #

```

Para diseñar la función de  hash, pueden asumir que para todos los puzzles se cumplirá que `2 < w <= 18` y `2 < h <= 18`. La cantidad de pasos no está acotada.

Puede ser útil para comparar los estados en la tabla de hash, guardar el valor de hash en lugar del estado en sí (dado que ya tienen que calcularlo). Esto solo funciona si la función de hash es perfecta. Para evitar perder datos, pueden usar la librería [GNU MP](https://gmplib.org/manual/Integer-Functions.html#Integer-Functions), para trabajar con numeros arbitrariamente grandes.

Para usarla deberían decir

``` c
#include <gmp.h>
```

Y en la Makefile poner en `LIB`, 

``` Makefile
LIB=-lm -lgmp
```

**Comment by DibPuelma** [comment]
La cantidad de bloques de hielo estará acotada??

**Comment by Ghoeb** [comment]
@DibPuelma por las dimensiones del tablero, claro.

**Comment by fariquelme** [comment]
Las orillas de los puzzles son siempre anti-hielo ?

**Comment by Ghoeb** [comment]
@fariquelme Sí

**Comment by mf222** [comment]
@Ghoeb no entiendo muy bien por qué usamos GNU MP. ¿Es para hacer los calculos de las funciones de hash? ¿Es demasiada la perdida si no usamos GNU MP? si es así, podrías dar un ejemplo de como usar la liberia. Estuve viendo la documentación y no entiendo bien como aplicarlo al problema :worried:
