### ISSUE TITLE
Consideración: Corregir también cell_type.h

### ISSUE THREAD

**Issue by djpassi** [IIC2133-PUC/2016-2#62]
En el _cell_type_ falta agregar los importantes bloques de hielo que se resfalan.

Por lo que aun que no esté especificado, no está demás pedir que corrijan este archivo producido por cada alumno y no sólo se corrija el main debido a que podemos usar distintos "apodos" para esta celda.

Saludos!

**Comment by djpassi** [comment]
Acabo de fijarme que esto lo hicieron a propósito quizás. 
Cambio la pregunta, por qué no agregaron el bloque de hielo a cell_type y tiene un comportamiento distinto al momento de querer mostrarlo en el watcher?

**Comment by Ghoeb** [comment]
Esto es porque los bloques de hielo son los únicos objetos que se mueven de una celda a otra, mientras que cada celda mantiene su tipo tenga o no un bloque de hielo encima. Por lo mismo, en el watcher los bloques de hielo tienen su propia función, ya que los otros jamás van a cambiar en el transcurso del programa (y han de volver a su tipo original cuando les sacas el hielo)

**Comment by djpassi** [comment]
Gracias

**Comment by djpassi** [comment]
Considero que sería buena idea igual tener en la grilla los bloques de hielo identificados.
Tener los bloques de hielo en un arreglo puede ser muy costoso para revisar si una jugada es legal o no debido a que cada vez que haga una jugada tengo que iterar sobre TODO el arreglo en vez de consultar al puzzle[x][y] si es que cierta celda en especifico es un objeto el cual no me deja hacer una jugada (en este caso bloque de hielo o muralla)

Puedo agregar al celltype el bloque de hielo o van a corregir el mismo para todos??

Gracias

**Comment by Ghoeb** [comment]
Si guardas en un arreglo los hielos cada hielo debe guardar solamente su posicion en x e y; luego para ver las jugadas validas sabes perfectamente que celdas del tablero revisar segun la posición de hielo. Haz las modificaciones que estimes pertinente, pero has de saber que tu tarea se ejecutará sin el watcher.

**Comment by djpassi** [comment]
Gracias de nuevo!
