### ISSUE TITLE
Movimiento posterior a choque de Bloques de Hielo

### ISSUE THREAD

**Issue by djpassi** [IIC2133-PUC/2016-2#63]
Que pasa si tenemos la siguiente situación (situación hipotética, no se puede llegar a ese estado con esa cantidad de bloques, pero si se tuviera más bloques se puede llegar a ese estado facilmente):
![5](https://cloud.githubusercontent.com/assets/13721150/19497000/7fb11a9a-9560-11e6-9998-dc482edd62a8.png)
Y se hace PUSH 2 3 D y queda de esta forma:
![6](https://cloud.githubusercontent.com/assets/13721150/19497001/7fb26710-9560-11e6-9292-e11396bab129.png)

Que pasa con el bloque que queda en (3,3)??

Se queda tal cual está? Que pasa si alguien lo choca después?

Gracias

**Comment by Ghoeb** [comment]
Se queda ahi donde está hasta que se lo empuje manualmente. Los bloques no se empujan entre ellos.

**Comment by djpassi** [comment]
Gracias, quedó claro
