### ISSUE TITLE
Algoritmo de búsqueda

### ISSUE THREAD

**Issue by ivanwolf15** [IIC2133-PUC/2016-2#64]
Hola, 
Se puede usar cualquier algoritmo de búsqueda o tiene que ser IDDFS? Me imagino que con búsqueda ciega no llegue a nada, pero puedo implementar A_, IDA_ o alguna variante? 
Saludos,

**Comment by alopez7** [comment]
Puedes implementar el algoritmo de búsqueda que quieras mientras uses una tabla de hash para almacenar tus estados. En tu informe tienes que explicar tu algoritmo y explicar por qué lo usaste.

**Comment by Ghoeb** [comment]
Osea, si no usas una tabla de hash no hay manera de que puedas encontrar la solución en el tiempo estipulado. Se propuso IDDFS porque ocupa menos memoria y es más simple de implementar.
