### ISSUE TITLE
Duda sobre tabla de hash

### ISSUE THREAD

**Issue by fjvaldes1** [IIC2133-PUC/2016-2#65]
Hola, 
En el algoritmo que estoy haciendo, estoy guardando en una tabla de hash los nodos que ya he visitado, para poder revisar en O(1) si podar una rama determinada o no (la podo si el resultado del hash es no nulo). Si es que esto está bien, ¿debería "resetear" la tabla de hash para cada iteración de DFS con profundidad máxima distinta? Porque si no la reseteo, al revisar los estados adyacentes al estado inicial obtendría que ya están todos hasheados, y por lo tanto cortaría todas las ramas disponibles y se acabaría ahí la búsqueda.

Probablemente estoy entendiendo mal el uso de la tabla de hash, agradecería mucho que me aclararan un poco el asunto.

**Comment by alopez7** [comment]
No deberías "podar" un estado solo por estar en la tabla. 
Se supone que debes guardar en la tabla de hash el número de pasos en los que llegaste al estado y alguna manera de representar el estado anterior o el camino para llegar a ese estado. 
De esta manera al llegar al estado otra vez, si llegas en una cantidad de pasos mayor, no expandes ese estado y "lo podas".
En el caso de llegar a un estado en el cual ya estuviste en una cantidad de pasos igual a la guardada, sigues expandiendo.
Mañana en la ayudantía puedo explicarlo de manera más gráfica.

**Comment by fjvaldes1** [comment]
Perfecto, gracias!
