### ISSUE TITLE
BFS vs ID-DFS

### ISSUE THREAD

**Issue by fjvaldes1** [IIC2133-PUC/2016-2#66]
Hola, tengo otra duda, no me queda claro cuál es la ventaja de usar ID-DFS sobre usar BFS.
Saludos

**Comment by Ghoeb** [comment]
IDDFS usa menos memoria, pero es un poco más lento. Por otro lado, BFS te exige necesariamente guardar los estados, y comparar estados es no trivial, mientras que en IDDFS puedes guardar el valor de hash de los estados y compararlos (suponiendo que tu función de hash es biyectiva / perfecta).

Se propuso IDDFS por que es más simple de implementar que BFS, pero eres libre de usar el que quieras.

**Comment by fjvaldes1** [comment]
Gracias por la respuesta, pero no entiendo cómo se puede hacer una función biyectiva/perfecta. En el caso del escenario más grande, que es de 18*18 según dijiste en otra issue, habrían más o menos 2^256 estados más o menos, suponiendo que los bordes son de antihielo (podrían haber menos por los bloques de piedra y más antihielos). Obviamente no podemos tener una tabla de hash de este tamaño, entonces ¿cómo se hace?

**Comment by CristianCn** [comment]
Me sumo a la pregunta, según lo que han dicho sería super conveniente tener una función de hash perfecta, hay alguna forma genérica de hacer esto? O en el caso de optar por una con colisiones entre diferentes estados cómo se puede establecer un buen tamaño del arreglo que guardará la función de hash?

Saludos!

**Comment by alopez7** [comment]
* En cuanto a como hace la función de hash perfecta, no podemos darles una pista tan grande. Deben pensar como transformar un estado del puzzle a un número dependiendo de las posiciones de los hielos.
* En cuanto a la tabla de hash, no deben hacer la tabla tan grande, ya que pueden haber demasiados estados. Lo que recomiendo es que dupliquen el tamaño de la tabla cuando se esté llenando, de esta manera el programa pedirá más memoria solo cuando lo necesite
* Como el tamaño de la tabla no es tan grande, muchos estados van a colisionar, por lo que deben manejar las colisiones con direccionamiento abierto o cerrado. La gracia de la función de hash perfecta no es que los estados no choquen en la tabla, sino que puedes comparar los hash de 2 estados y saber instantáneamente si son estados iguales. Es por esto que en la tabla solo debes guardar la cantidad de pasos en los que llegaste al estado, y el hash mismo.

Espero responda sus dudas

**Comment by Ghoeb** [comment]
Para poder guardar los valores de hash tan grandes, van a necesitar trabajar con GMP necesariamente. Si no quieren usar la librería, entonces tendrán que guardar el estado del tablero en sí, y ver otra forma de compararlos de manera eficiente.
