### ISSUE TITLE
Sobre el acceso a la tabla de hash

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#67]
Hola: mi duda es si será recomendable implementar cada cosa con listas ligadas o hay algo que funcione mejor? Pregunto porque me imagino que si la tabla crece mucho, acceder a un determinado nodo puede hacerse relativamente lento.
Muchas gracias!

**Comment by Ghoeb** [comment]
Ambos métodos de manejo de colisiones son buenos, pero en este caso recomiendo especialmente usar direccionamiento abierto. La justificación a eso es parte de tu informe, por lo que no te la puedo dar. 

Saludos!
