### ISSUE TITLE
Movimiento de Hielo hacia un Botón

### ISSUE THREAD

**Issue by carlosgarciag** [IIC2133-PUC/2016-2#68]
Tengo una duda sobre el movimiento de los hielos cuando llegan a un botón. Al tener este caso:

# # # # #
# H o _ #
# # # # #

Si muevo H a la derecha, ¿Quedaría así? (opción A)

# # # # #
# _ H _ #
# # # # #

¿o así? (opción B)

# # # # #
# _ o H#
# # # # #

Muchas gracias

**Comment by alopez7** [comment]
Queda como la opción B, el botón no para al hielo

**Comment by carlosgarciag** [comment]
Gracias @alopez7  :+1:
