### ISSUE TITLE
Sobre subir puzzles y snapshots con la tarea

### ISSUE THREAD

**Issue by pdpino** [IIC2133-PUC/2016-2#69]
Hola!

Me fijé que en el .gitignore del repositorio de la T3 no aparecen las extensiones .png (snapshots de la interfaz) ni .txt (puzzles).  ¿Subimos estos archivos al repo? ¿los eliminamos/agregamos las extensiones al .gitignore? ¿da igual?

**Comment by Ghoeb** [comment]
Agradecería que no los subieran, asi usamos menos espacio.

**Comment by vaopaso** [comment]
¿Es obligatorio implementar la solución con la librería watcher y sacando snapshots, o sólo importa el output txt con las instrucciones push?
En caso que haya que hacerlo con el watcher, ¿cada snapshot corresponde a cada estado o a cada movimiento de bloques (o sea puede ser más de una foto entre dos estados) ?

**Comment by alopez7** [comment]
El watcher es solo para el debug. Su output es el archivo
