### ISSUE TITLE
Memory leaks al referenciar imagenes

### ISSUE THREAD

**Issue by mf222** [IIC2133-PUC/2016-2#7]
Hola! Estoy tratando de solucionar lo de los memory leaks que se crean al hacer ` Image_rgb *image = load_image_rgb(argv[1]);`. Trate con `free(image)` pero sigo teniendo las perdidas de memoria. En imagelib.c hay 2 callocs que no se liberan (pero se supone que son lo que recibo en main.c). Como podría liberar la memoria desde el main entonces? hay alguna otra función?

**Comment by gafigueroa** [comment]
Hola, no entendí a que te refieres con que los recibes desde el main.

¿Los 2 callocs que dices son ```image->pixels = calloc(image->width, sizeof(Pixel_rgb*));``` y ```image->pixels[x] = calloc(image->height, sizeof(Pixel_rgb));```?

Si la respuesta es si, al hacer ```free(image)``` solo estás liberando el puntero a la dirección de memoria de la imagen, pero los otros elementos siguen alocados. 

Estos igual los debes liberar, es decir para cada elemento en pixels debes hacer ```free(image->pixels[x])```, luego liberar el array ```free(image->pixels)``` y finalmente liberar la imagen.

Espero ese haya sido el problema, saludos.

**Comment by mf222** [comment]
¡Gracias! era eso mismo a lo que me referia :) ahora libero bien todo :confetti_ball:  tenia la confusión de que con el puntero liberaba todo, pero era más complejo de lo que imaginaba :/

Saludos!

**Comment by vjgardul** [comment]
hola, en este mismo contexto, mi leak summary se tiene errores en suppressed y el detalle referencia cosas de mac os. Leyendo en internet dice que no debería importar ¿es porque ocupo mac o tiene arreglo?

==14622== HEAP SUMMARY:
==14622==     in use at exit: 22,546 bytes in 188 blocks
==14622==   total heap usage: 1,352 allocs, 1,164 frees, 6,518,776 bytes allocated
==14622== 
==14622== Searching for pointers to 188 not-freed blocks
==14622== Checked 9,812,224 bytes
==14622== 
==14622== LEAK SUMMARY:
==14622==    definitely lost: 0 bytes in 0 blocks
==14622==    indirectly lost: 0 bytes in 0 blocks
==14622==      possibly lost: 0 bytes in 0 blocks
==14622==    still reachable: 0 bytes in 0 blocks
==14622==         suppressed: 22,546 bytes in 188 blocks
==14622== 
==14622== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 17 from 17)
--14622-- 
--14622-- used_suppression:      1 OSX1011:21-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:944 suppressed: 4,096 bytes in 1 blocks
--14622-- used_suppression:     11 OSX1011:5-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:787 suppressed: 3,408 bytes in 56 blocks
--14622-- used_suppression:      3 OSX1011:16-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:897 suppressed: 2,816 bytes in 44 blocks
--14622-- used_suppression:      2 OSX1011:4-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:778 suppressed: 4,152 bytes in 2 blocks
--14622-- used_suppression:      4 OSX1011:19-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:924 suppressed: 3,656 bytes in 4 blocks
--14622-- used_suppression:      3 OSX1011:18-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:915 suppressed: 2,064 bytes in 3 blocks
--14622-- used_suppression:     19 OSX1011:10-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:839 suppressed: 2,898 bytes in 38 blocks
--14622-- used_suppression:      2 OSX1011:8-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:819 suppressed: 520 bytes in 2 blocks
--14622-- used_suppression:      6 OSX1011:7-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:808 suppressed: 720 bytes in 24 blocks
--14622-- used_suppression:      2 OSX1011:20-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:934 suppressed: 224 bytes in 5 blocks
--14622-- used_suppression:      8 OSX1011:6-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:797 suppressed: 248 bytes in 8 blocks
--14622-- used_suppression:      1 OSX1011:17-Leak /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/default.supp:906 suppressed: 32 bytes in 1 blocks
==14622== 
==14622== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 17 from 17)

**Comment by Ghoeb** [comment]
@vjgardul me da la impresion de que es por Mac. Ve si te da el mismo nivel de errores en un simple "Hello World!". Igual puedes irte a la segura probandolo en Ubuntu.

**Comment by vjgardul** [comment]
@Ghoeb voy a revisarlo gracias!
