### ISSUE TITLE
Sobre el IDDFS

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#70]
Hola! Tengo la siguiente duda: cuando hacemos el algoritmo IDDFS, la idea de dicho algoritmo es que, para una siguiente iteración, parta revisando de los nodos que ya había revisado, o tiene que partir de cero? Ejemplo, si se descubrieron 200 nodos hasta la iteración 7, ¿la iteración 8 podría sólo considerar partir de los nodos descubiertos en la 7ma iteración? (Pregunto porque no sé si el algoritmo se vuelve demasiado engorroso implementando esto).
Espero se entienda
Muchas gracias!

**Comment by Ghoeb** [comment]
Si no aprovechas lo de las iteraciones pasadas, el algoritmo se vuelve muy lento; ya estás revisando los estados conocidos, revisar la información de iteraciones pasadas te sale gratis en ese contexto.

**Comment by AlfonsoIgnacioV** [comment]
Tengo otra duda... en algún momento se mencionó que el algoritmo podía encontrar, en una misma iteración, dos veces el mismo nodo, pero encontrarlo con un costo menor la segunda vez. ¿Por qué? Estaba pensando en que en cada iteración n se encuentran nodos cuya mínima ruta es n. Entonces, ¿no debería ser imposible si fue encontrado con n, ser luego encontrado en esa iteración con costo menor que n? Quiero decir, si tal fuera el caso, debería haberse encontrado en una iteración anterior, o no es así?
Muchas gracias
