### ISSUE TITLE
Otra duda sobre IDDFS

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#71]
Tengo otra duda... en algún momento se mencionó que el algoritmo podía encontrar, en una misma iteración, dos veces el mismo nodo, pero encontrarlo con un costo menor la segunda vez. ¿Por qué? Estaba pensando en que en cada iteración n se encuentran nodos cuya mínima ruta es n. Entonces, ¿no debería ser imposible si fue encontrado con n, ser luego encontrado en esa iteración con costo menor que n? Quiero decir, si tal fuera el caso, debería haberse encontrado en una iteración anterior, o no es así?
Muchas gracias

**Comment by Ghoeb** [comment]
Dentro de una misma iteración puedes encontrar un mismo estado desde una ruta más larga que la optima, en ese caso no debes entrar. Pero lo mejor a lo que puedes aspirar es a encontrar el estado por una ruta igual de larga que la óptima, dado que la óptima fue encontrada en la iteración anterior.
