### ISSUE TITLE
Hash perfecto con tamaño dinámico

### ISSUE THREAD

**Issue by icrocco** [IIC2133-PUC/2016-2#72]
Hola,

Basado en un issue anterior veo que se recomienda (o más bien propone) usar una función de hash perfecta para llevar registro de las visitas anteriores. Por otra parte, recuerdo que en una ayudantía se recomendó que el tamaño de la tabla de hash fuera creciendo conforme se iba llenando, para optimizar el uso de memoria. 

Ahora bien, si tengo un valor único para cada posible estado,  pero el tamaño de la tabla en determinado momento es menor que el total de estados no tengo como asegurar (o por lo menos no he podido yo) que no hayan colisiones ¿es posible tener ambas ventajas o hay que escoger una?.

**Comment by icrocco** [comment]
Aaah, creo que ya entendí! :sweat_smile:

La función de hash perfecta se refiere a que cada estado se codifique con un valor distinto, independiente de que al aplicar el módulo después para guardarlo en la tabla puedan haber colisiones, no?

**Comment by Ghoeb** [comment]
Exacto, es eso mismo. Que sea perfecta significa que puedes guardar el valor de hash en la tabla, en lugar del estado en sí.
