### ISSUE TITLE
Respuestas Test

### ISSUE THREAD

**Issue by spiza** [IIC2133-PUC/2016-2#73]
Para corroborar nuestras respuestas, propongo (al igual que para la T1) que subamos acá nuestras respuestas..

Espero que los ayudantes den visto bueno antes de publicar respuestas.

Saludos

**Comment by alopez7** [comment]
No se pueden publicar las respuestas de las tareas ya que el método de recorrección permite hacer cambios a los códigos. Si hay una respuesta que funciona publicada, el alumno puede usar el código de uno de sus compañeros.

**Comment by spiza** [comment]
:(

Enviado desde mi iPhone

**Comment by alopez7** [comment]
Perdón, pensé que te referías a tu Código. Pueden subir sus soluciones con su número de pasos y tiempo.

**Comment by spiza** [comment]
:)

Enviado desde mi iPhone

**Comment by spiza** [comment]
Test 1
5
7
# # # # #
# _ _ H #
# _ _ _ #
# _ o _ #
# _ _ _ #
# H _ H #
# # # # #

Respuesta

7
push 5 3 U
push 2 3 L
push 1 3 D
push 5 1 U
push 2 1 R
push 5 3 U
push 3 1 R


Test 2
6
6
# # # # # #
# X _ _ H #
# _ o _ _ #
# _ _ o _ #
# H _ _ H #
# # # # # #

Respuesta

10
push 1 4 D
push 4 1 U
push 4 4 L
push 4 1 U
push 3 1 R
push 3 4 D
push 2 1 R
push 4 4 L
push 4 1 U
push 2 4 L

Test 3
7
7
# # # # # # #
# _ _ _ _ H #
# _ _ _ _ _ #
# _ _ o _ _ #
# _ _ _ _ _ #
# H _ _ _ H #
# # # # # # #

Respuesta 
11
push 5 5 U
push 2 5 L
push 1 5 D
push 5 1 U
push 2 1 R
push 5 5 U
push 3 5 L
push 3 1 D
push 5 1 R
push 5 5 U
push 3 5 L

**Comment by sedelacerda** [comment]
**Test 1**

7
push 5 3 U
push 2 3 L
push 1 3 D
push 5 1 U
push 2 1 R
push 5 3 U
push 3 3 L

**Test 2**

10
push 1 4 D
push 4 1 U
push 3 4 L
push 2 1 R
push 4 4 U
push 3 1 R
push 3 4 D
push 4 4 L
push 4 1 U
push 2 4 L

**Test 3**

11
push 5 5 U
push 2 5 L
push 1 5 D
push 5 1 U
push 2 1 R
push 5 5 U
push 3 5 L
push 3 1 D
push 5 1 R
push 5 5 U
push 3 5 L

**Comment by spiza** [comment]
Ufff... y el tiempo? Me gustaría ganarme
El bonus x velocidad 

Enviado desde mi iPhone

**Comment by sedelacerda** [comment]
Acabo de sacarle la interfaz grafica y se demora mucho menos :smile: 

**Test 1**

real	0m0.021s
user	0m0.024s
sys	0m0.000s

**Test 2**

real	0m0.422s
user	0m0.420s
sys	0m0.004s

**Test 3**

real	0m3.294s
user	0m3.292s
sys	0m0.004s


Y tu? Parece que no me interesa el bonus pero quiero saber si es muy lento compardo al resto por que en escala el tiempo es medio exponencial segun yo.

**Comment by spiza** [comment]
Test 1:

0.01s user 0.00s system 78% cpu 0.011 total


Test 2:

0.03s user 0.01s system 42% cpu 0.072 total

Test 3:

0.06s user 0.01s system 59% cpu 0.118 total

:P

**Comment by Arios16** [comment]
### Test 1
7
push 5 3 U
push 2 3 L
push 1 3 D
push 5 1 U
push 2 1 R
push 5 3 U
push 3 3 L

real	0m0.002s
user	0m0.000s
sys	0m0.000s

### Test 2
10
push 1 4 D
push 4 1 U
push 4 4 L
push 4 1 U
push 3 1 R
push 3 4 D
push 4 4 L
push 2 1 R
push 4 1 U
push 2 4 L

real	0m0.003s
user	0m0.000s
sys	0m0.000s

### Test 3
11
push 5 5 L
push 5 2 U
push 1 5 L
push 5 1 R
push 1 2 D
push 5 5 L
push 5 3 U
push 1 3 R
push 1 5 D
push 5 5 L
push 5 3 U

real	0m0.005s
user	0m0.004s
sys	0m0.000s

Pero estos tests son muy faciles :p Probemos con algo un poco más grande:

## Test 4
    8
    8
    # # # # # # # #
    # _ _ _ _ o o #
    # _ _ _ o o _ #
    # H _ _ o _ _ #
    # _ H _ _ _ _ #
    # H _ H _ _ _ #
    # _ H _ _ _ _ #
    # # # # # # # #

Respuesta:
12
push 4 2 U
push 6 2 U
push 5 3 R
push 5 1 R
push 5 6 U
push 1 2 R
push 3 1 U
push 5 5 U
push 1 1 R
push 1 4 D
push 2 2 R
push 6 4 U

real	0m0.240s
user	0m0.236s
sys	0m0.000s

## Test 5
    14
    14
    # # # # # # # # # # # # # #
    # o _ _ _ _ _ _ o _ _ _ H #
    # _ X _ _ _ _ _ _ _ _ _ _ #
    # _ X _ _ _ _ _ _ _ _ H H #
    # _ X _ _ _ X _ _ _ _ o _ #
    # _ X _ _ _ _ _ _ _ _ _ X #
    # _ X o _ _ _ _ _ _ _ _ o #
    # _ _ X _ _ _ _ _ _ _ _ _ #
    # _ _ _ _ _ _ _ _ _ _ _ _ #
    # _ _ _ _ _ _ _ _ _ H _ _ #
    # _ _ _ _ _ _ _ _ _ o _ _ #
    # _ _ _ _ _ _ _ _ _ _ _ _ #
    # _ _ _ H _ _ _ _ _ _ H _ #
    # # # # # # # # # # # # # #

Respuesta:

14
push 3 12 D
push 4 12 L
push 4 7 U
push 12 4 R
push 12 11 U
push 12 10 U
push 1 12 L
push 9 10 L
push 3 11 L
push 9 1 U
push 3 3 D
push 1 7 D
push 12 7 R
push 12 12 U

real	0m2.229s
user	0m2.208s
sys	0m0.020s

¿Cuanto se demoran en estos dos?

**Comment by DibPuelma** [comment]
La volaita 😅

**Comment by DibPuelma** [comment]
El mío ni resuelve los 2 que pusiste @Arios16 , ni idea por q la verdad. Con los otros no tengo problemas 😕

**Comment by spiza** [comment]
.... Son demasiado jarcor.. Si no usas heurísticas y weás, no se resuelven..

En todo caso, yo tampoco los puedo resolver, jajjaa.. Pero TODOS SABEMOS que ninguno de los tests será así de difícil, porque sino solo arios tendría todo bueno

**Comment by DibPuelma** [comment]
@spiza lograste resolver lo de valgrind? Me tiene enfermo jejeje

**Comment by spiza** [comment]
La verdad es que me rendí.. me dio paja hacer todo, y decidí no usar la interfaz, jajajaj

**Comment by DibPuelma** [comment]
Dale, a ver si el vicho me contesta. Gracias igual!

**Comment by Ghoeb** [comment]
@Arios16 lo hiciste con A* / ID-A*, no? Porque la solución usa sólo ID-DFS jajaja

##### Test 1: 7 pasos, 237 estados expandidos

real	0m0.006s
user	0m0.000s
sys	0m0.004s

##### Test 2: 10 pasos, 338 estados expandidos

real	0m0.039s
user	0m0.004s
sys	0m0.000s

##### Test 3: 11 pasos, 922 estados expandidos

real	0m0.040s
user	0m0.012s
sys	0m0.000s

##### Test 4: 12 pasos, 148591 estados expandidos

real	0m2.305s
user	0m2.276s
sys	0m0.028s

##### Test 5: 14 pasos, 25451440 estados expandidos

real	6m7.374s
user	6m2.680s
sys	0m3.940s

Huele a bonus XD!

**Comment by Arios16** [comment]
@Ghoeb Si, lo hice con A* 😄

@DibPuelma @spiza El test 5 probablemente sea más de lo que van a pedir, pero el test 4 es muy razonable (pueden ver que la solución IDDFS de Vicente lo resuelve en 2.3 segundos), por lo que igual deberían intentar optimizar su algoritmo para resolverlo.

**Comment by spiza** [comment]
Nah, el test 4 es 150 veces más complejo que el test 3.. 

Enviado desde mi iPhone

**Comment by alopez7** [comment]
No se confíen, el test 4 si está dentro del rango de test que podríamos poner

**Comment by orrios** [comment]
**test 1: 7 pasos**
0.00user 0.00system 0:00.00elapsed 0%CPU

**test 2: 10 pasos**
0.00user 0.00system 0:00.00elapsed 100%CPU

**test 3: 11 pasos**
0.00user 0.00system 0:00.01elapsed 72%CPU

**test 4: 12 pasos**
1.22user 0.01system 0:01.23elapsed 100%CPU

**test 5: 14 pasos**
:thinking: 3032.27user 22.68system 50:55.06elapsed 99%CPU :thinking: 
Como que me explota un poquito...

Pero al menos es más rápido en tests fáciles ![image](https://cloud.githubusercontent.com/assets/11396718/19978426/a895f0b2-a1d5-11e6-9656-f72fec312e45.png)

@alopez7  @Ghoeb ¿podrían dar un ejemplo tipo test difícil para ver si me despreocupo o no?

**Comment by alopez7** [comment]
La verdad no hemos definido cuales son los test con que vamos a evaluar, pero no te debería preocuar porque tu programa es más rápido que el de vicho

**Comment by spiza** [comment]
Pero el Vicho es el ayudante master supremo... me parece que si su programa le toma 3 segundos, es bastante alta la exigencia, en especial considerando que el tomo las buenas prácticas

Enviado desde mi iPhone

**Comment by Ghoeb** [comment]
@spiza las soluciones las escribo pensando en codigo que ustedes deberían ser capaces de escribir, asique de repente me salto un par de buenas prácticas para simplificarlo...

**Comment by fariquelme** [comment]
Test 1
5
7
# # # # #
# _ _ H #
# _ _ _ #
# _ o _ #
# _ _ _ #
# H _ H #
# # # # #


7
push 5 3 U
push 2 3 L
push 1 3 D
push 5 1 U
push 2 1 R
push 5 3 U
push 3 1 R

Generated States : 922, Expanded states : 218

real	0m0.068s
user	0m0.010s
sys	0m0.017s

Test 2
6
6
# # # # # #
# X _ _ H #
# _ o _ _ #
# _ _ o _ #
# H _ _ H #
# # # # # #

10
push 1 4 D
push 4 1 U
push 4 4 L
push 4 1 U
push 3 1 R
push 3 4 D
push 4 4 L
push 2 1 R
push 4 1 U
push 2 4 L

Generated States : 1581, Expanded states : 331

real	0m0.062s
user	0m0.010s
sys	0m0.015s

Test 3

7
7
# # # # # # #
# _ _ _ _ H #
# _ _ _ _ _ #
# _ _ o _ _ #
# _ _ _ _ _ #
# H _ _ _ H #
# # # # # # #

11
push 5 5 L
push 5 2 U
push 1 5 L
push 5 1 R
push 1 2 D
push 5 5 L
push 5 3 U
push 1 3 R
push 1 5 D
push 5 5 L
push 5 3 U

Generated States : 5509, Expanded states : 918

real	0m0.059s
user	0m0.012s
sys	0m0.015s

Test 4

8
8
# # # # # # # #
# _ _ _ _ o o #
# _ _ _ o o _ #
# H _ _ o _ _ #
# _ H _ _ _ _ #
# H _ H _ _ _ #
# _ H _ _ _ _ #
# # # # # # # #

12
push 5 3 R
push 5 1 R
push 5 6 U
push 3 1 U
push 1 1 R
push 5 5 U
push 4 2 U
push 6 2 U
push 1 2 R
push 1 4 D
push 2 2 R
push 6 4 U

Generated States : 103652, Expanded states : 29153

real	0m0.251s
user	0m0.185s
sys	0m0.032s

Test 5

14
14
# # # # # # # # # # # # # #
# o _ _ _ _ _ _ o _ _ _ H #
# _ X _ _ _ _ _ _ _ _ _ _ #
# _ X _ _ _ _ _ _ _ _ H H #
# _ X _ _ _ X _ _ _ _ o _ #
# _ X _ _ _ _ _ _ _ _ _ X #
# _ X o _ _ _ _ _ _ _ _ o #
# _ _ X _ _ _ _ _ _ _ _ _ #
# _ _ _ _ _ _ _ _ _ _ _ _ #
# _ _ _ _ _ _ _ _ _ H _ _ #
# _ _ _ _ _ _ _ _ _ o _ _ #
# _ _ _ _ _ _ _ _ _ _ _ _ #
# _ _ _ H _ _ _ _ _ _ H _ #
# # # # # # # # # # # # # #

14
14
push 12 4 R
push 1 1 R
push 1 1 R
push 1 1 R
push 1 1 R
push 3 11 L
push 1 1 R
push 4 7 U
push 1 12 L
push 9 10 R
push 9 12 U
push 1 8 D
push 1 7 L
push 12 8 U

Generated States : 401242, Expanded states : 168077

real	0m0.888s
user	0m0.754s
sys	0m0.071s

**Comment by Arios16** [comment]
@fariquelme Solo por si acaso, la solución que posteaste para el último test está mala :confused: Haces 'push 1 1 R' varias veces seguidas, siendo que ni siquiera había un bloque en (1,1) para empezar.

**Comment by spiza** [comment]
Woow, alguien pensó que había perdido su bonus 

Enviado desde mi iPhone

**Comment by fariquelme** [comment]
@Arios16  Verdad!  Gracias no había cachado el bug.
