### ISSUE TITLE
Mas ejemplos (?)

### ISSUE THREAD

**Issue by sedelacerda** [IIC2133-PUC/2016-2#75]
Podrian subir ejemplos que requieran una mayor cantidad de pasos para ser resueltos? En los cuales se tenga que usar IDDFS hasta una profundidad mayor que en los ejemplos que se subieron anteriormente.

**Comment by alopez7** [comment]
No se si te sirva que demos una cantidad máxima de pasos, ya que el tiempo depende de los pasos y de la ramificación del problema (número de hielos)

**Comment by sedelacerda** [comment]
Sii porfa, tambien me sirve :D
