### ISSUE TITLE
computador correccion

### ISSUE THREAD

**Issue by orrios** [IIC2133-PUC/2016-2#77]
Hola!!
Todo es mas eficiente si es que parto con una hash table más grande! :grimacing: 
Cuanta memoria tiene el computador que se usará para la corrección?
Es el mismo que el se usó para anteriores?

Saludos!

**Comment by alopez7** [comment]
Es el mismo computador que se usó en las otras correcciones. No recomiendo fijar un tamaño de tabla inicial. Es mejor agrandar la tabla cuando se necesite

**Comment by orrios** [comment]
@alopez7 oka!
si, si agrando la tabla pero para problemas medianos - chicos el costo de hacer rehashing es muy grande.
la idea es poder resolver los tests del 1 al 4 de los posteados por @Arios16 en #73 sin necesidad de hacer rehash.
Es claro que el test 5 se va en volá y ahí tengo que hacer unos cuantos rehashes.

Saludos!

**Comment by alopez7** [comment]
Claro, puedes partir con una tabla de tamaño grande y luego agrandarla si es necesario. Eso lo puedes analizar en tu informe

**Comment by orrios** [comment]
oka! gracias!
