### ISSUE TITLE
Distinción entre Iteración y pasos 

### ISSUE THREAD

**Issue by CristianCn** [IIC2133-PUC/2016-2#78]
En la ayudantía se dijo que en la tabla de hash se debía guardar el número de iteración en que estoy y el número de pasos para alcanzar ese estado. No entiendo bien esta diferencia y cuando serían distintos.

Por ejemplo en el siguiente algoritmo de IDDFS general para grafos cuál sería el numero de pasos y cúal la iteración?

```
procedure IDDFS(root)
    for depth from 0 to ∞
        found ← DLS(root, depth)
        if found ≠ null
            return found

procedure DLS(node, depth)
    if depth = 0 and node is a goal
        return node
    if depth > 0
        foreach child of node
            found ← DLS(child, depth−1)
            if found ≠ null
                return found
    return null
```

Gracias!

**Comment by Ghoeb** [comment]
Como dice el nombre, IDDFS es un algoritmo Iterativo. La variable `depth` marca la iteracion en la que vas. DLS así como lo tienes definido no sirve, ya que no tienes como saber en que iteracion de IDDFS vas. 

Debe usarse

DLS (estado, profundidad actual, profundidad límite) 

y cambiar el caso base de la recursión.

**Comment by CristianCn** [comment]
Sería algo de la siguiente forma?

```
procedure IDDFS(root)
    for iteracion from 0 to ∞
        pasos ← 0
        found ← DLS(root, pasos, iteracion)
        if found ≠ null
            return found

procedure DLS(node, pasos, iteracion)
    if pasos = iteracion and node is a goal
        return node
    if pasos < iteracion
        foreach child of node
            found ← DLS(child, pasos ++)
            if found ≠ null
                return found
    return null
```

Se que no aplica el algoritmo para el problema, pero es para ver si entendí la diferencia entre pasos e iteración y el algoritmo sería una adaptación de esto, saludos!

**Comment by Ghoeb** [comment]
Algo así, aunque tienes dos errores en la llamada recursiva a DLS:

1) Es `pasos+1` no `pasos++` dado que quieres que pasos aumente en la subinstancia de la funcion, y no en el scope actual.
2) Falta agregarle el tercer parámetro

**Comment by CristianCn** [comment]
gracias!
