### ISSUE TITLE
Tamaño tabla de hash

### ISSUE THREAD

**Issue by jlires** [IIC2133-PUC/2016-2#79]
¿Cuánto se considera grande para el tamaño de inicio de la tabla? ¿2**12 (¿o más aún?) es grande o está bien?

**Comment by Ghoeb** [comment]
2^12 es un numero razonable, aunque aconsejo usar numeros primos para los tamaños de la tabla de hash.

**Comment by jlires** [comment]
:+1:  El número era para dar una idea.
