### ISSUE TITLE
[Librería GMP] Fallo al compilar

### ISSUE THREAD

**Issue by PDono19** [IIC2133-PUC/2016-2#80]
Hola, puede que sea un error muy tonto mio pero ya he tratado todo y no logro hacer funcionar la librería.
Ya la he instalado y todo pero al hacer make en mi programa me sale el siguiente error:

 main.c:(.text+0x1a19): referencia a `__gmpz_init' sin definir
main.c:(.text+0x1a25): referencia a `__gmpz_init' sin definir
main.c:(.text+0x1a31): referencia a `__gmpz_init' sin definir
collect2: error: ld returned 1 exit status

Tengo agregada la librería con #include <gmp.h> e inicializado los enteros grandes con mpz_t.

Ojala puedan ayudarme, necesito arreglar esto para recién poder probar mi programa jajaja 

Gracias!

**Comment by Ghoeb** [comment]
No has puesto `-lgmp` en LIB= en tu Makefile

**Comment by PDono19** [comment]
GRACIAS!!! era eso jajaj
