### ISSUE TITLE
Dudas del informe

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [IIC2133-PUC/2016-2#81]
En la parte donde se pide hablar sobre la función de hash (la que tiene 4 puntos), ¿cuál es el nivel de detalle solicitado? Lo pregunto porque son preguntas bastante directas de contestar, pero no sé cuál es el nivel de análisis que se espera.
Muchas gracias!

**Comment by Ghoeb** [comment]
No nos sirve que te saques respuestas del sombrero. Aunque sean respuestas cortas, tienen que estar bien justificadas.
