### ISSUE TITLE
Complejidad librería GMP

### ISSUE THREAD

**Issue by fjvaldes1** [IIC2133-PUC/2016-2#82]
Hola, tengo la siguiente duda:

Cuando piden analizar el costo de calcular nuestra función de hash, ¿se puede asumir que las operaciones de números mpz_t toman tiempo constante? Por ejemplo sumas, restas, potencias, módulo, etc.

Gracias!

**Comment by Ghoeb** [comment]
Ok. Pero es importante que tengas claro que eso no es cierto.

**Comment by fjvaldes1** [comment]
Vale, gracias!
