### ISSUE TITLE
Rúbrica Tarea 3

### ISSUE THREAD

**Issue by carlosgarciag** [IIC2133-PUC/2016-2#87]
Estimados ayudantes,

Estaba viendo que la rúbrica de la tarea 3 en la sección código es bastante tajante. De hecho me di cuenta que si no es la misma cantidad de pasos que la respuesta óptima, el puntaje es cero en ese test y punto. Entendiendo que SÍ se llega a una solución -y varios le metimos mucha cabeza a la tarea aprendiendo y quizás eso debería ser premiado de alguna manera- ¿Es posible que puedan reevaluar la puntuación? por ejemplo, si es la misma cantidad de pasos, luego tienes 100%, si tienes un paso más 75%, dos más 50%, 3 más 25%, más de 3 10% -o cualquier escala que ustedes crean más justa.

Por favor considérenlo. La tarea en sí era difícil y es una pena que no se premie al menos haber llegado a una solución en el tiempo máximo que dieron.

De antemano, muchísimas gracias.

**Comment by Ghoeb** [comment]
Lo que pasa es que si encontraste una secuencia no óptima de pasos, entonces estás haciendo cualquier cosa para buscar la solución; las secuencias largas de pasos son muchísimo más fáciles de encontrar que las óptimas, por lo que claramente vas a poder encontrarlas dentro del tiempo límite.

Así que no, lo siento pero se evaluará según lo descrito en el enunciado. Los que quieran arreglar su nota, que arreglen su código.

Saludos!
