### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by afgil** [IIC2133-PUC/2016-2#9]
Hola, 
No me queda claro en algunos casos cómo se tienen que extender los valores que se salen de la imagen. Por ejemplo, qué pasaría si tengo la misma matriz del enunciado:

| 1 	| 2 	| 3 	|
|---	|---	|---	|
| 4 	| 5 	| 6 	|
| 7 	| 8 	| 9 	|

y le aplicamos un filtro de dx=0 dy=1. ¿Cómo quedaría la primera fila? (en el caso azul que se mueve dx y dy)  

Y como quedaría la misma matriz pero con un filtro de dx=1 dy=1?

Saludos,

**Comment by Ghoeb** [comment]
En el caso de dx = 0, dy = 1

R =

| 4 	| 5 	| 6 	|
| :---:	 | :---: | :---: |
| 7	| 8 	| 9 	|
| 7 	| 8 	| 9 	|

G = 

| 1 	| 2 	| 3 	|
| :---: | :---: | :---: |
| 4 	| 5 	| 6 	|
| 7 	| 8 	| 9 	|

B = 

| 1 	| 2 	| 3 	|
| :---: | :---: | :---: |
| 1 	| 2 	| 3 	|
| 4 	| 5 	| 6 	|

--------------------

Y en el caso de dx = 1, dy = 1

R = 

| 5 	| 6 	| 6 	|
| :---: | :---: | :---: |
| 8 	| 9 	| 9 	|
| 8 	| 9 	| 9 	|

G = 

| 1 	| 2 	| 3 	|
| :---: | :---: | :---: |
| 4 	| 5 	| 6 	|
| 7 	| 8 	| 9 	|

B = 

| 1 	| 1 	| 2 	|
| :---: | :---: | :---: |
| 1 	| 1 	| 2 	|
| 4 	| 4 	| 5 	|

**Comment by afgil** [comment]
Gracias me quedó claro,
Saludos
