### ISSUE TITLE
Test Tarea 4

### ISSUE THREAD

**Issue by VictorVidaurre** [IIC2133-PUC/2016-2#91]
Van a subir algunos tests para probar la tarea? Para tener alguna idea de las dimensiones de los tableros y sus complejidades.

**Comment by vdrg** [comment]
Hola, les subí unos tests, un script para crear tableros, y un judge para que revisen si sus soluciones efectivamente resuelven sus tableros. 

Los tests van a ser muy simples, y ningún test se demorará más de unos pocos segundos con la pauta.

**Comment by vjgardul** [comment]
Hola, con simples se entiende 'no mas grandes que los tests que subieron' o mas simples q esos? gracias :)
