### ISSUE TITLE
Orden en grafo inicial

### ISSUE THREAD

**Issue by djpassi** [IIC2133-PUC/2016-2#92]
Hola, 

Dos preguntas:

1. El nodo "padre" puede ser distinto en los distintos casos según cómo se programe. Van a considerar eso?

Ocupando el ejemplo del enunciado el grupo `4 | (2,0) 2 # 5 : 1 2 5 7 8` tiene nodo "padre" al nodo `(2,0)` y en mi caso debido a que recorro la matriz de distinta forma es `4 | (1,1) 2 # 5 : 1 2 5 7 8` de forma igualmente válida.

2. Los grupos adyacentes pueden ir en desorden? Con esto me refiero a:

`2 | (0,3) 1 # 5 : 3 4 1 6 5` (desordenado básicamente) en vez de cómo está en el enunciado de esta forma:

`2 | (0,3) 1 # 5 : 1 3 4 5 6`

Saludos,

**Comment by alopez7** [comment]
Si, lo que importa es que el punto de la grilla que guarda cada nodo sea de un grupo de colores distinto y que las aristas que relacionan esos grupos estén correctas.

**Comment by djpassi** [comment]
Gracias!
