### ISSUE TITLE
error judge.py

### ISSUE THREAD

**Issue by orrios** [IIC2133-PUC/2016-2#93]
Hola!
Si no me equivoco, hay un error en el programa que revisa la solución.
En la linea 12:
       ` if (x < 0 or x >= len(board[0]) or y < 0 or y >= len(board)):`
Donde x es la fila e y la columna, board es una lista de todas las filas.
Entonces se va out of bound cuando no son boards cuadradas.
Deberia ser:
        `if (x < 0 or x >= len(board) or y < 0 or y >= len(board[0])):`
Saludos!

**Comment by vdrg** [comment]
hola! efectivamente había un error, pero no el que tú dices. De todas formas, gracias por avisar!

**Comment by vdrg** [comment]
Ahora si. Tenías razón! disculpa, he dormido poco jaja 

Saludos
