### ISSUE TITLE
Output graph.txt T4

### ISSUE THREAD

**Issue by icrocco** [IIC2133-PUC/2016-2#94]
¡Hola!

¿No hay problema con que el orden en que se presentan los resultados en graph.txt no sean (de)crecientes, pero respetando el formato?

Me refiero a obtener:
<pre>
8
8 | (5,2) 0 # 3 : 6 7 4
7 | (4,1) 1 # 4 : 8 6 5 4
6 | (3,4) 3 # 4 : 8 7 2 5
5 | (2,2) 0 # 4 : 7 6 2 4
4 | (1,1) 2 # 5 : 8 7 5 2 1
3 | (0,6) 2 # 1 : 2
2 | (0,3) 1 # 5 : 6 5 4 3 1
1 | (0,0) 0 # 2 : 4 2
</pre>

En lugar de lo que nos dieron como ejemplo:
<pre>
8
1 | (0,0) 0 # 2 : 2 4
2 | (0,3) 1 # 5 : 1 3 4 5 6
3 | (0,6) 2 # 1 : 2
4 | (2,0) 2 # 5 : 1 2 5 7 8
5 | (2,2) 0 # 4 : 2 4 6 7
6 | (3,4) 3 # 4 : 2 5 7 8
7 | (4,1) 1 # 4 : 4 5 6 8
8 | (5,2) 0 # 3 : 4 7 6
</pre>
¡Gracias!

**Comment by vdrg** [comment]
No hay problema con eso.

Saludos
